{
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Setup"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [],
   "source": [
    "# python standard\n",
    "import os\n",
    "\n",
    "# third party\n",
    "import numpy as np\n",
    "import pandas as pd\n",
    "import seaborn as sns\n",
    "import tzlocal\n",
    "from pylab import rcParams\n",
    "from matplotlib import pyplot\n",
    "%matplotlib inline\n",
    "import rpy2.robjects as robjects\n",
    "\n",
    "%load_ext rpy2.ipython"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "metadata": {},
   "outputs": [],
   "source": [
    "rcParams['figure.figsize'] = 22, 7\n",
    "rcParams['axes.titlesize'] = 20\n",
    "rcParams['xtick.labelsize'] = 18\n",
    "rcParams['ytick.labelsize'] = 14\n",
    "rcParams['legend.fontsize'] = 14\n",
    "rcParams['axes.formatter.useoffset'] = False\n",
    "\n",
    "# Files/paths\n",
    "# msg_data_path = '/n/holylfs/LABS/hoekstra_lab/hoekstrafs3/bendesky/genotyping/msg/'\n",
    "# lib_path = '/n/holylfs/LABS/hoekstra_lab/hoekstrafs3/bendesky/genotyping/physical_map/lib'\n",
    "\n",
    "# msg_run = os.path.join(msg_data_path, '20151111')\n",
    "# combine_dir = os.path.join(msg_run, 'combine-difffac_0.1')\n",
    "# rqtl_dir = os.path.join(msg_run, 'rqtl', 'EPM')\n",
    "\n",
    "# # Files for rqtl\n",
    "# cross_path = os.path.join(rqtl_dir, 'cross_EPM_newChromNames_2017.RData')\n",
    "# # Files for read.cross.msg\n",
    "# read_cross_file1 = os.path.join(combine_dir, 'ancestry-probs-par2.tsv.sorted.csv')\n",
    "# read_cross_file2 = os.path.join(combine_dir, 'ancestry-probs-par2.tsv.sorted.pulled.converted.thinned.f2_rqtl')\n",
    "# EPM_pheno_file = '/n/holylfs/LABS/hoekstra_lab/hoekstrafs3/EPM/results/rqtl_epm_pheno_file.csv'\n",
    "# ancfile_par1 = os.path.join(combine_dir, 'ancestry-probs-par1.tsv.sorted.pulled.converted.thinned.f2_rqtl')\n",
    "\n",
    "cross_path = 'cross_EPM_newChromNames_2017.RData'\n",
    "\n",
    "# Libraries\n",
    "# r_package_path = os.path.join(lib_path, 'Rpackages')\n",
    "\n",
    "\n",
    "\n"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Import R Data"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 9,
   "metadata": {},
   "outputs": [],
   "source": [
    "%%R\n",
    "# To load qtl you must have the qtl library installed in R\n",
    "library(qtl)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 10,
   "metadata": {},
   "outputs": [],
   "source": [
    "%%R -i cross_path\n",
    "load(cross_path)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 12,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       " [1] \"id\"                      \"sex\"                    \n",
       " [3] \"frac_in_closedAndMiddle\" \"frac_in_closedArms\"     \n",
       " [5] \"frac_in_middle\"          \"frac_in_openArms\"       \n",
       " [7] \"entries_to_closed\"       \"entries_to_open\"        \n",
       " [9] \"distance_in_closed\"      \"distance_in_open\"       \n",
       "[11] \"speed_in_closed\"         \"speed_in_open\"          \n",
       "[13] \"entries_o_c_ratio\"       \"distance_o_c_ratio\"     \n",
       "[15] \"speed_o_c_ratio\"         \"total_frames\"           \n",
       "[17] \"tested_more_than_once\"   \"pgm\"                    \n",
       "[19] \"frac_entries_to_open\"    \"frac_distance_in_open\"  \n",
       "[21] \"log_temp_pheno\"         \n"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    }
   ],
   "source": [
    "%%R\n",
    "# Current Phenotypes\n",
    "print(names(cross$pheno))"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Merge R Data with New Features"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 21,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/Users/joshfeldman/Desktop/Projects/mice/venv/lib/python3.6/site-packages/rpy2/robjects/pandas2ri.py:191: FutureWarning: from_items is deprecated. Please use DataFrame.from_dict(dict(items), ...) instead. DataFrame.from_dict(OrderedDict(items)) may be used to preserve the key order.\n",
      "  res = PandasDataFrame.from_items(items)\n",
      "/Users/joshfeldman/Desktop/Projects/mice/venv/lib/python3.6/site-packages/rpy2/robjects/pandas2ri.py:67: UserWarning: Error while trying to convert the column \"id\". Fall back to string conversion. The error is: Conversion 'py2ri' not defined for objects of type '<class 'pandas.core.series.Series'>'\n",
      "  (name, str(e)))\n",
      "/Users/joshfeldman/Desktop/Projects/mice/venv/lib/python3.6/site-packages/rpy2/robjects/pandas2ri.py:67: UserWarning: Error while trying to convert the column \"sex\". Fall back to string conversion. The error is: Conversion 'py2ri' not defined for objects of type '<class 'pandas.core.series.Series'>'\n",
      "  (name, str(e)))\n",
      "/Users/joshfeldman/Desktop/Projects/mice/venv/lib/python3.6/site-packages/rpy2/robjects/pandas2ri.py:67: UserWarning: Error while trying to convert the column \"frac_in_closedAndMiddle\". Fall back to string conversion. The error is: Conversion 'py2ri' not defined for objects of type '<class 'pandas.core.series.Series'>'\n",
      "  (name, str(e)))\n",
      "/Users/joshfeldman/Desktop/Projects/mice/venv/lib/python3.6/site-packages/rpy2/robjects/pandas2ri.py:67: UserWarning: Error while trying to convert the column \"frac_in_closedArms\". Fall back to string conversion. The error is: Conversion 'py2ri' not defined for objects of type '<class 'pandas.core.series.Series'>'\n",
      "  (name, str(e)))\n",
      "/Users/joshfeldman/Desktop/Projects/mice/venv/lib/python3.6/site-packages/rpy2/robjects/pandas2ri.py:67: UserWarning: Error while trying to convert the column \"frac_in_middle\". Fall back to string conversion. The error is: Conversion 'py2ri' not defined for objects of type '<class 'pandas.core.series.Series'>'\n",
      "  (name, str(e)))\n",
      "/Users/joshfeldman/Desktop/Projects/mice/venv/lib/python3.6/site-packages/rpy2/robjects/pandas2ri.py:67: UserWarning: Error while trying to convert the column \"frac_in_openArms\". Fall back to string conversion. The error is: Conversion 'py2ri' not defined for objects of type '<class 'pandas.core.series.Series'>'\n",
      "  (name, str(e)))\n",
      "/Users/joshfeldman/Desktop/Projects/mice/venv/lib/python3.6/site-packages/rpy2/robjects/pandas2ri.py:67: UserWarning: Error while trying to convert the column \"entries_to_closed\". Fall back to string conversion. The error is: Conversion 'py2ri' not defined for objects of type '<class 'pandas.core.series.Series'>'\n",
      "  (name, str(e)))\n",
      "/Users/joshfeldman/Desktop/Projects/mice/venv/lib/python3.6/site-packages/rpy2/robjects/pandas2ri.py:67: UserWarning: Error while trying to convert the column \"entries_to_open\". Fall back to string conversion. The error is: Conversion 'py2ri' not defined for objects of type '<class 'pandas.core.series.Series'>'\n",
      "  (name, str(e)))\n",
      "/Users/joshfeldman/Desktop/Projects/mice/venv/lib/python3.6/site-packages/rpy2/robjects/pandas2ri.py:67: UserWarning: Error while trying to convert the column \"distance_in_closed\". Fall back to string conversion. The error is: Conversion 'py2ri' not defined for objects of type '<class 'pandas.core.series.Series'>'\n",
      "  (name, str(e)))\n",
      "/Users/joshfeldman/Desktop/Projects/mice/venv/lib/python3.6/site-packages/rpy2/robjects/pandas2ri.py:67: UserWarning: Error while trying to convert the column \"distance_in_open\". Fall back to string conversion. The error is: Conversion 'py2ri' not defined for objects of type '<class 'pandas.core.series.Series'>'\n",
      "  (name, str(e)))\n",
      "/Users/joshfeldman/Desktop/Projects/mice/venv/lib/python3.6/site-packages/rpy2/robjects/pandas2ri.py:67: UserWarning: Error while trying to convert the column \"speed_in_closed\". Fall back to string conversion. The error is: Conversion 'py2ri' not defined for objects of type '<class 'pandas.core.series.Series'>'\n",
      "  (name, str(e)))\n",
      "/Users/joshfeldman/Desktop/Projects/mice/venv/lib/python3.6/site-packages/rpy2/robjects/pandas2ri.py:67: UserWarning: Error while trying to convert the column \"speed_in_open\". Fall back to string conversion. The error is: Conversion 'py2ri' not defined for objects of type '<class 'pandas.core.series.Series'>'\n",
      "  (name, str(e)))\n",
      "/Users/joshfeldman/Desktop/Projects/mice/venv/lib/python3.6/site-packages/rpy2/robjects/pandas2ri.py:67: UserWarning: Error while trying to convert the column \"entries_o_c_ratio\". Fall back to string conversion. The error is: Conversion 'py2ri' not defined for objects of type '<class 'pandas.core.series.Series'>'\n",
      "  (name, str(e)))\n",
      "/Users/joshfeldman/Desktop/Projects/mice/venv/lib/python3.6/site-packages/rpy2/robjects/pandas2ri.py:67: UserWarning: Error while trying to convert the column \"distance_o_c_ratio\". Fall back to string conversion. The error is: Conversion 'py2ri' not defined for objects of type '<class 'pandas.core.series.Series'>'\n",
      "  (name, str(e)))\n",
      "/Users/joshfeldman/Desktop/Projects/mice/venv/lib/python3.6/site-packages/rpy2/robjects/pandas2ri.py:67: UserWarning: Error while trying to convert the column \"speed_o_c_ratio\". Fall back to string conversion. The error is: Conversion 'py2ri' not defined for objects of type '<class 'pandas.core.series.Series'>'\n",
      "  (name, str(e)))\n",
      "/Users/joshfeldman/Desktop/Projects/mice/venv/lib/python3.6/site-packages/rpy2/robjects/pandas2ri.py:67: UserWarning: Error while trying to convert the column \"total_frames\". Fall back to string conversion. The error is: Conversion 'py2ri' not defined for objects of type '<class 'pandas.core.series.Series'>'\n",
      "  (name, str(e)))\n",
      "/Users/joshfeldman/Desktop/Projects/mice/venv/lib/python3.6/site-packages/rpy2/robjects/pandas2ri.py:67: UserWarning: Error while trying to convert the column \"tested_more_than_once\". Fall back to string conversion. The error is: Conversion 'py2ri' not defined for objects of type '<class 'pandas.core.series.Series'>'\n",
      "  (name, str(e)))\n",
      "/Users/joshfeldman/Desktop/Projects/mice/venv/lib/python3.6/site-packages/rpy2/robjects/pandas2ri.py:67: UserWarning: Error while trying to convert the column \"pgm\". Fall back to string conversion. The error is: Conversion 'py2ri' not defined for objects of type '<class 'pandas.core.series.Series'>'\n",
      "  (name, str(e)))\n",
      "/Users/joshfeldman/Desktop/Projects/mice/venv/lib/python3.6/site-packages/rpy2/robjects/pandas2ri.py:67: UserWarning: Error while trying to convert the column \"frac_entries_to_open\". Fall back to string conversion. The error is: Conversion 'py2ri' not defined for objects of type '<class 'pandas.core.series.Series'>'\n",
      "  (name, str(e)))\n",
      "/Users/joshfeldman/Desktop/Projects/mice/venv/lib/python3.6/site-packages/rpy2/robjects/pandas2ri.py:67: UserWarning: Error while trying to convert the column \"frac_distance_in_open\". Fall back to string conversion. The error is: Conversion 'py2ri' not defined for objects of type '<class 'pandas.core.series.Series'>'\n",
      "  (name, str(e)))\n",
      "/Users/joshfeldman/Desktop/Projects/mice/venv/lib/python3.6/site-packages/rpy2/robjects/pandas2ri.py:67: UserWarning: Error while trying to convert the column \"log_temp_pheno\". Fall back to string conversion. The error is: Conversion 'py2ri' not defined for objects of type '<class 'pandas.core.series.Series'>'\n",
      "  (name, str(e)))\n",
      "/Users/joshfeldman/Desktop/Projects/mice/venv/lib/python3.6/site-packages/rpy2/robjects/pandas2ri.py:67: UserWarning: Error while trying to convert the column \"mouseID\". Fall back to string conversion. The error is: Conversion 'py2ri' not defined for objects of type '<class 'pandas.core.series.Series'>'\n",
      "  (name, str(e)))\n",
      "/Users/joshfeldman/Desktop/Projects/mice/venv/lib/python3.6/site-packages/rpy2/robjects/pandas2ri.py:67: UserWarning: Error while trying to convert the column \"backtrack_counts_CL\". Fall back to string conversion. The error is: Conversion 'py2ri' not defined for objects of type '<class 'pandas.core.series.Series'>'\n",
      "  (name, str(e)))\n",
      "/Users/joshfeldman/Desktop/Projects/mice/venv/lib/python3.6/site-packages/rpy2/robjects/pandas2ri.py:67: UserWarning: Error while trying to convert the column \"backtrack_counts_CR\". Fall back to string conversion. The error is: Conversion 'py2ri' not defined for objects of type '<class 'pandas.core.series.Series'>'\n",
      "  (name, str(e)))\n",
      "/Users/joshfeldman/Desktop/Projects/mice/venv/lib/python3.6/site-packages/rpy2/robjects/pandas2ri.py:67: UserWarning: Error while trying to convert the column \"backtrack_counts_OB\". Fall back to string conversion. The error is: Conversion 'py2ri' not defined for objects of type '<class 'pandas.core.series.Series'>'\n",
      "  (name, str(e)))\n",
      "/Users/joshfeldman/Desktop/Projects/mice/venv/lib/python3.6/site-packages/rpy2/robjects/pandas2ri.py:67: UserWarning: Error while trying to convert the column \"backtrack_counts_OT\". Fall back to string conversion. The error is: Conversion 'py2ri' not defined for objects of type '<class 'pandas.core.series.Series'>'\n",
      "  (name, str(e)))\n",
      "/Users/joshfeldman/Desktop/Projects/mice/venv/lib/python3.6/site-packages/rpy2/robjects/pandas2ri.py:67: UserWarning: Error while trying to convert the column \"backtrack_counts_total\". Fall back to string conversion. The error is: Conversion 'py2ri' not defined for objects of type '<class 'pandas.core.series.Series'>'\n",
      "  (name, str(e)))\n",
      "/Users/joshfeldman/Desktop/Projects/mice/venv/lib/python3.6/site-packages/rpy2/robjects/pandas2ri.py:67: UserWarning: Error while trying to convert the column \"backtrack_counts_total_closed\". Fall back to string conversion. The error is: Conversion 'py2ri' not defined for objects of type '<class 'pandas.core.series.Series'>'\n",
      "  (name, str(e)))\n",
      "/Users/joshfeldman/Desktop/Projects/mice/venv/lib/python3.6/site-packages/rpy2/robjects/pandas2ri.py:67: UserWarning: Error while trying to convert the column \"backtrack_counts_total_open\". Fall back to string conversion. The error is: Conversion 'py2ri' not defined for objects of type '<class 'pandas.core.series.Series'>'\n",
      "  (name, str(e)))\n",
      "/Users/joshfeldman/Desktop/Projects/mice/venv/lib/python3.6/site-packages/rpy2/robjects/pandas2ri.py:67: UserWarning: Error while trying to convert the column \"fraction_in_arms_bottom\". Fall back to string conversion. The error is: Conversion 'py2ri' not defined for objects of type '<class 'pandas.core.series.Series'>'\n",
      "  (name, str(e)))\n",
      "/Users/joshfeldman/Desktop/Projects/mice/venv/lib/python3.6/site-packages/rpy2/robjects/pandas2ri.py:67: UserWarning: Error while trying to convert the column \"fraction_in_arms_closed\". Fall back to string conversion. The error is: Conversion 'py2ri' not defined for objects of type '<class 'pandas.core.series.Series'>'\n",
      "  (name, str(e)))\n",
      "/Users/joshfeldman/Desktop/Projects/mice/venv/lib/python3.6/site-packages/rpy2/robjects/pandas2ri.py:67: UserWarning: Error while trying to convert the column \"fraction_in_arms_closed_and_middle\". Fall back to string conversion. The error is: Conversion 'py2ri' not defined for objects of type '<class 'pandas.core.series.Series'>'\n",
      "  (name, str(e)))\n",
      "/Users/joshfeldman/Desktop/Projects/mice/venv/lib/python3.6/site-packages/rpy2/robjects/pandas2ri.py:67: UserWarning: Error while trying to convert the column \"fraction_in_arms_left\". Fall back to string conversion. The error is: Conversion 'py2ri' not defined for objects of type '<class 'pandas.core.series.Series'>'\n",
      "  (name, str(e)))\n",
      "/Users/joshfeldman/Desktop/Projects/mice/venv/lib/python3.6/site-packages/rpy2/robjects/pandas2ri.py:67: UserWarning: Error while trying to convert the column \"fraction_in_arms_middle\". Fall back to string conversion. The error is: Conversion 'py2ri' not defined for objects of type '<class 'pandas.core.series.Series'>'\n",
      "  (name, str(e)))\n",
      "/Users/joshfeldman/Desktop/Projects/mice/venv/lib/python3.6/site-packages/rpy2/robjects/pandas2ri.py:67: UserWarning: Error while trying to convert the column \"fraction_in_arms_open-arms\". Fall back to string conversion. The error is: Conversion 'py2ri' not defined for objects of type '<class 'pandas.core.series.Series'>'\n",
      "  (name, str(e)))\n",
      "/Users/joshfeldman/Desktop/Projects/mice/venv/lib/python3.6/site-packages/rpy2/robjects/pandas2ri.py:67: UserWarning: Error while trying to convert the column \"fraction_in_arms_right\". Fall back to string conversion. The error is: Conversion 'py2ri' not defined for objects of type '<class 'pandas.core.series.Series'>'\n",
      "  (name, str(e)))\n",
      "/Users/joshfeldman/Desktop/Projects/mice/venv/lib/python3.6/site-packages/rpy2/robjects/pandas2ri.py:67: UserWarning: Error while trying to convert the column \"fraction_in_arms_top\". Fall back to string conversion. The error is: Conversion 'py2ri' not defined for objects of type '<class 'pandas.core.series.Series'>'\n",
      "  (name, str(e)))\n",
      "/Users/joshfeldman/Desktop/Projects/mice/venv/lib/python3.6/site-packages/rpy2/robjects/pandas2ri.py:67: UserWarning: Error while trying to convert the column \"frames_in_arms_CL\". Fall back to string conversion. The error is: Conversion 'py2ri' not defined for objects of type '<class 'pandas.core.series.Series'>'\n",
      "  (name, str(e)))\n",
      "/Users/joshfeldman/Desktop/Projects/mice/venv/lib/python3.6/site-packages/rpy2/robjects/pandas2ri.py:67: UserWarning: Error while trying to convert the column \"frames_in_arms_CR\". Fall back to string conversion. The error is: Conversion 'py2ri' not defined for objects of type '<class 'pandas.core.series.Series'>'\n",
      "  (name, str(e)))\n",
      "/Users/joshfeldman/Desktop/Projects/mice/venv/lib/python3.6/site-packages/rpy2/robjects/pandas2ri.py:67: UserWarning: Error while trying to convert the column \"frames_in_arms_M\". Fall back to string conversion. The error is: Conversion 'py2ri' not defined for objects of type '<class 'pandas.core.series.Series'>'\n",
      "  (name, str(e)))\n",
      "/Users/joshfeldman/Desktop/Projects/mice/venv/lib/python3.6/site-packages/rpy2/robjects/pandas2ri.py:67: UserWarning: Error while trying to convert the column \"frames_in_arms_OB\". Fall back to string conversion. The error is: Conversion 'py2ri' not defined for objects of type '<class 'pandas.core.series.Series'>'\n",
      "  (name, str(e)))\n",
      "/Users/joshfeldman/Desktop/Projects/mice/venv/lib/python3.6/site-packages/rpy2/robjects/pandas2ri.py:67: UserWarning: Error while trying to convert the column \"frames_in_arms_OT\". Fall back to string conversion. The error is: Conversion 'py2ri' not defined for objects of type '<class 'pandas.core.series.Series'>'\n",
      "  (name, str(e)))\n",
      "/Users/joshfeldman/Desktop/Projects/mice/venv/lib/python3.6/site-packages/rpy2/robjects/pandas2ri.py:67: UserWarning: Error while trying to convert the column \"inner_directory\". Fall back to string conversion. The error is: Conversion 'py2ri' not defined for objects of type '<class 'pandas.core.series.Series'>'\n",
      "  (name, str(e)))\n",
      "/Users/joshfeldman/Desktop/Projects/mice/venv/lib/python3.6/site-packages/rpy2/robjects/pandas2ri.py:67: UserWarning: Error while trying to convert the column \"mouse_details_EPM\". Fall back to string conversion. The error is: Conversion 'py2ri' not defined for objects of type '<class 'pandas.core.series.Series'>'\n",
      "  (name, str(e)))\n",
      "/Users/joshfeldman/Desktop/Projects/mice/venv/lib/python3.6/site-packages/rpy2/robjects/pandas2ri.py:67: UserWarning: Error while trying to convert the column \"mouse_details_date\". Fall back to string conversion. The error is: Conversion 'py2ri' not defined for objects of type '<class 'pandas.core.series.Series'>'\n",
      "  (name, str(e)))\n",
      "/Users/joshfeldman/Desktop/Projects/mice/venv/lib/python3.6/site-packages/rpy2/robjects/pandas2ri.py:67: UserWarning: Error while trying to convert the column \"mouse_details_mouseID\". Fall back to string conversion. The error is: Conversion 'py2ri' not defined for objects of type '<class 'pandas.core.series.Series'>'\n",
      "  (name, str(e)))\n",
      "/Users/joshfeldman/Desktop/Projects/mice/venv/lib/python3.6/site-packages/rpy2/robjects/pandas2ri.py:67: UserWarning: Error while trying to convert the column \"mouse_details_sex\". Fall back to string conversion. The error is: Conversion 'py2ri' not defined for objects of type '<class 'pandas.core.series.Series'>'\n",
      "  (name, str(e)))\n",
      "/Users/joshfeldman/Desktop/Projects/mice/venv/lib/python3.6/site-packages/rpy2/robjects/pandas2ri.py:67: UserWarning: Error while trying to convert the column \"mouse_details_strain\". Fall back to string conversion. The error is: Conversion 'py2ri' not defined for objects of type '<class 'pandas.core.series.Series'>'\n",
      "  (name, str(e)))\n",
      "/Users/joshfeldman/Desktop/Projects/mice/venv/lib/python3.6/site-packages/rpy2/robjects/pandas2ri.py:67: UserWarning: Error while trying to convert the column \"mouse_details_time\". Fall back to string conversion. The error is: Conversion 'py2ri' not defined for objects of type '<class 'pandas.core.series.Series'>'\n",
      "  (name, str(e)))\n",
      "/Users/joshfeldman/Desktop/Projects/mice/venv/lib/python3.6/site-packages/rpy2/robjects/pandas2ri.py:67: UserWarning: Error while trying to convert the column \"mouse_length\". Fall back to string conversion. The error is: Conversion 'py2ri' not defined for objects of type '<class 'pandas.core.series.Series'>'\n",
      "  (name, str(e)))\n",
      "/Users/joshfeldman/Desktop/Projects/mice/venv/lib/python3.6/site-packages/rpy2/robjects/pandas2ri.py:67: UserWarning: Error while trying to convert the column \"peeking_average_length_CL\". Fall back to string conversion. The error is: Conversion 'py2ri' not defined for objects of type '<class 'pandas.core.series.Series'>'\n",
      "  (name, str(e)))\n",
      "/Users/joshfeldman/Desktop/Projects/mice/venv/lib/python3.6/site-packages/rpy2/robjects/pandas2ri.py:67: UserWarning: Error while trying to convert the column \"peeking_average_length_CR\". Fall back to string conversion. The error is: Conversion 'py2ri' not defined for objects of type '<class 'pandas.core.series.Series'>'\n",
      "  (name, str(e)))\n",
      "/Users/joshfeldman/Desktop/Projects/mice/venv/lib/python3.6/site-packages/rpy2/robjects/pandas2ri.py:67: UserWarning: Error while trying to convert the column \"peeking_average_length_total\". Fall back to string conversion. The error is: Conversion 'py2ri' not defined for objects of type '<class 'pandas.core.series.Series'>'\n",
      "  (name, str(e)))\n",
      "/Users/joshfeldman/Desktop/Projects/mice/venv/lib/python3.6/site-packages/rpy2/robjects/pandas2ri.py:67: UserWarning: Error while trying to convert the column \"peeking_count_CL\". Fall back to string conversion. The error is: Conversion 'py2ri' not defined for objects of type '<class 'pandas.core.series.Series'>'\n",
      "  (name, str(e)))\n",
      "/Users/joshfeldman/Desktop/Projects/mice/venv/lib/python3.6/site-packages/rpy2/robjects/pandas2ri.py:67: UserWarning: Error while trying to convert the column \"peeking_count_CR\". Fall back to string conversion. The error is: Conversion 'py2ri' not defined for objects of type '<class 'pandas.core.series.Series'>'\n",
      "  (name, str(e)))\n",
      "/Users/joshfeldman/Desktop/Projects/mice/venv/lib/python3.6/site-packages/rpy2/robjects/pandas2ri.py:67: UserWarning: Error while trying to convert the column \"peeking_count_total\". Fall back to string conversion. The error is: Conversion 'py2ri' not defined for objects of type '<class 'pandas.core.series.Series'>'\n",
      "  (name, str(e)))\n",
      "/Users/joshfeldman/Desktop/Projects/mice/venv/lib/python3.6/site-packages/rpy2/robjects/pandas2ri.py:67: UserWarning: Error while trying to convert the column \"peeking_fraction_CL\". Fall back to string conversion. The error is: Conversion 'py2ri' not defined for objects of type '<class 'pandas.core.series.Series'>'\n",
      "  (name, str(e)))\n",
      "/Users/joshfeldman/Desktop/Projects/mice/venv/lib/python3.6/site-packages/rpy2/robjects/pandas2ri.py:67: UserWarning: Error while trying to convert the column \"peeking_fraction_CR\". Fall back to string conversion. The error is: Conversion 'py2ri' not defined for objects of type '<class 'pandas.core.series.Series'>'\n",
      "  (name, str(e)))\n",
      "/Users/joshfeldman/Desktop/Projects/mice/venv/lib/python3.6/site-packages/rpy2/robjects/pandas2ri.py:67: UserWarning: Error while trying to convert the column \"peeking_fraction_total\". Fall back to string conversion. The error is: Conversion 'py2ri' not defined for objects of type '<class 'pandas.core.series.Series'>'\n",
      "  (name, str(e)))\n",
      "/Users/joshfeldman/Desktop/Projects/mice/venv/lib/python3.6/site-packages/rpy2/robjects/pandas2ri.py:67: UserWarning: Error while trying to convert the column \"peeking_median_length_CL\". Fall back to string conversion. The error is: Conversion 'py2ri' not defined for objects of type '<class 'pandas.core.series.Series'>'\n",
      "  (name, str(e)))\n",
      "/Users/joshfeldman/Desktop/Projects/mice/venv/lib/python3.6/site-packages/rpy2/robjects/pandas2ri.py:67: UserWarning: Error while trying to convert the column \"peeking_median_length_CR\". Fall back to string conversion. The error is: Conversion 'py2ri' not defined for objects of type '<class 'pandas.core.series.Series'>'\n",
      "  (name, str(e)))\n",
      "/Users/joshfeldman/Desktop/Projects/mice/venv/lib/python3.6/site-packages/rpy2/robjects/pandas2ri.py:67: UserWarning: Error while trying to convert the column \"peeking_median_length_total\". Fall back to string conversion. The error is: Conversion 'py2ri' not defined for objects of type '<class 'pandas.core.series.Series'>'\n",
      "  (name, str(e)))\n",
      "/Users/joshfeldman/Desktop/Projects/mice/venv/lib/python3.6/site-packages/rpy2/robjects/pandas2ri.py:67: UserWarning: Error while trying to convert the column \"rest_fraction_CL\". Fall back to string conversion. The error is: Conversion 'py2ri' not defined for objects of type '<class 'pandas.core.series.Series'>'\n",
      "  (name, str(e)))\n",
      "/Users/joshfeldman/Desktop/Projects/mice/venv/lib/python3.6/site-packages/rpy2/robjects/pandas2ri.py:67: UserWarning: Error while trying to convert the column \"rest_fraction_CR\". Fall back to string conversion. The error is: Conversion 'py2ri' not defined for objects of type '<class 'pandas.core.series.Series'>'\n",
      "  (name, str(e)))\n",
      "/Users/joshfeldman/Desktop/Projects/mice/venv/lib/python3.6/site-packages/rpy2/robjects/pandas2ri.py:67: UserWarning: Error while trying to convert the column \"rest_fraction_M\". Fall back to string conversion. The error is: Conversion 'py2ri' not defined for objects of type '<class 'pandas.core.series.Series'>'\n",
      "  (name, str(e)))\n",
      "/Users/joshfeldman/Desktop/Projects/mice/venv/lib/python3.6/site-packages/rpy2/robjects/pandas2ri.py:67: UserWarning: Error while trying to convert the column \"rest_fraction_OB\". Fall back to string conversion. The error is: Conversion 'py2ri' not defined for objects of type '<class 'pandas.core.series.Series'>'\n",
      "  (name, str(e)))\n",
      "/Users/joshfeldman/Desktop/Projects/mice/venv/lib/python3.6/site-packages/rpy2/robjects/pandas2ri.py:67: UserWarning: Error while trying to convert the column \"rest_fraction_OT\". Fall back to string conversion. The error is: Conversion 'py2ri' not defined for objects of type '<class 'pandas.core.series.Series'>'\n",
      "  (name, str(e)))\n",
      "/Users/joshfeldman/Desktop/Projects/mice/venv/lib/python3.6/site-packages/rpy2/robjects/pandas2ri.py:67: UserWarning: Error while trying to convert the column \"rest_fraction_all_arms\". Fall back to string conversion. The error is: Conversion 'py2ri' not defined for objects of type '<class 'pandas.core.series.Series'>'\n",
      "  (name, str(e)))\n",
      "/Users/joshfeldman/Desktop/Projects/mice/venv/lib/python3.6/site-packages/rpy2/robjects/pandas2ri.py:67: UserWarning: Error while trying to convert the column \"rest_fraction_closed_arms\". Fall back to string conversion. The error is: Conversion 'py2ri' not defined for objects of type '<class 'pandas.core.series.Series'>'\n",
      "  (name, str(e)))\n",
      "/Users/joshfeldman/Desktop/Projects/mice/venv/lib/python3.6/site-packages/rpy2/robjects/pandas2ri.py:67: UserWarning: Error while trying to convert the column \"rest_fraction_open_arms\". Fall back to string conversion. The error is: Conversion 'py2ri' not defined for objects of type '<class 'pandas.core.series.Series'>'\n",
      "  (name, str(e)))\n",
      "/Users/joshfeldman/Desktop/Projects/mice/venv/lib/python3.6/site-packages/rpy2/robjects/pandas2ri.py:67: UserWarning: Error while trying to convert the column \"safety_and_rest_fraction_CL\". Fall back to string conversion. The error is: Conversion 'py2ri' not defined for objects of type '<class 'pandas.core.series.Series'>'\n",
      "  (name, str(e)))\n",
      "/Users/joshfeldman/Desktop/Projects/mice/venv/lib/python3.6/site-packages/rpy2/robjects/pandas2ri.py:67: UserWarning: Error while trying to convert the column \"safety_and_rest_fraction_CR\". Fall back to string conversion. The error is: Conversion 'py2ri' not defined for objects of type '<class 'pandas.core.series.Series'>'\n",
      "  (name, str(e)))\n",
      "/Users/joshfeldman/Desktop/Projects/mice/venv/lib/python3.6/site-packages/rpy2/robjects/pandas2ri.py:67: UserWarning: Error while trying to convert the column \"safety_and_rest_fraction_closed_arms\". Fall back to string conversion. The error is: Conversion 'py2ri' not defined for objects of type '<class 'pandas.core.series.Series'>'\n",
      "  (name, str(e)))\n",
      "/Users/joshfeldman/Desktop/Projects/mice/venv/lib/python3.6/site-packages/rpy2/robjects/pandas2ri.py:67: UserWarning: Error while trying to convert the column \"safety_fraction_CL\". Fall back to string conversion. The error is: Conversion 'py2ri' not defined for objects of type '<class 'pandas.core.series.Series'>'\n",
      "  (name, str(e)))\n",
      "/Users/joshfeldman/Desktop/Projects/mice/venv/lib/python3.6/site-packages/rpy2/robjects/pandas2ri.py:67: UserWarning: Error while trying to convert the column \"safety_fraction_CR\". Fall back to string conversion. The error is: Conversion 'py2ri' not defined for objects of type '<class 'pandas.core.series.Series'>'\n",
      "  (name, str(e)))\n",
      "/Users/joshfeldman/Desktop/Projects/mice/venv/lib/python3.6/site-packages/rpy2/robjects/pandas2ri.py:67: UserWarning: Error while trying to convert the column \"safety_fraction_closed_arms\". Fall back to string conversion. The error is: Conversion 'py2ri' not defined for objects of type '<class 'pandas.core.series.Series'>'\n",
      "  (name, str(e)))\n",
      "/Users/joshfeldman/Desktop/Projects/mice/venv/lib/python3.6/site-packages/rpy2/robjects/pandas2ri.py:67: UserWarning: Error while trying to convert the column \"tot_arm_entries_CL\". Fall back to string conversion. The error is: Conversion 'py2ri' not defined for objects of type '<class 'pandas.core.series.Series'>'\n",
      "  (name, str(e)))\n",
      "/Users/joshfeldman/Desktop/Projects/mice/venv/lib/python3.6/site-packages/rpy2/robjects/pandas2ri.py:67: UserWarning: Error while trying to convert the column \"tot_arm_entries_CR\". Fall back to string conversion. The error is: Conversion 'py2ri' not defined for objects of type '<class 'pandas.core.series.Series'>'\n",
      "  (name, str(e)))\n",
      "/Users/joshfeldman/Desktop/Projects/mice/venv/lib/python3.6/site-packages/rpy2/robjects/pandas2ri.py:67: UserWarning: Error while trying to convert the column \"tot_arm_entries_F1\". Fall back to string conversion. The error is: Conversion 'py2ri' not defined for objects of type '<class 'pandas.core.series.Series'>'\n",
      "  (name, str(e)))\n",
      "/Users/joshfeldman/Desktop/Projects/mice/venv/lib/python3.6/site-packages/rpy2/robjects/pandas2ri.py:67: UserWarning: Error while trying to convert the column \"tot_arm_entries_F2\". Fall back to string conversion. The error is: Conversion 'py2ri' not defined for objects of type '<class 'pandas.core.series.Series'>'\n",
      "  (name, str(e)))\n",
      "/Users/joshfeldman/Desktop/Projects/mice/venv/lib/python3.6/site-packages/rpy2/robjects/pandas2ri.py:67: UserWarning: Error while trying to convert the column \"tot_arm_entries_F3\". Fall back to string conversion. The error is: Conversion 'py2ri' not defined for objects of type '<class 'pandas.core.series.Series'>'\n",
      "  (name, str(e)))\n",
      "/Users/joshfeldman/Desktop/Projects/mice/venv/lib/python3.6/site-packages/rpy2/robjects/pandas2ri.py:67: UserWarning: Error while trying to convert the column \"tot_arm_entries_F4\". Fall back to string conversion. The error is: Conversion 'py2ri' not defined for objects of type '<class 'pandas.core.series.Series'>'\n",
      "  (name, str(e)))\n",
      "/Users/joshfeldman/Desktop/Projects/mice/venv/lib/python3.6/site-packages/rpy2/robjects/pandas2ri.py:67: UserWarning: Error while trying to convert the column \"tot_arm_entries_M\". Fall back to string conversion. The error is: Conversion 'py2ri' not defined for objects of type '<class 'pandas.core.series.Series'>'\n",
      "  (name, str(e)))\n",
      "/Users/joshfeldman/Desktop/Projects/mice/venv/lib/python3.6/site-packages/rpy2/robjects/pandas2ri.py:67: UserWarning: Error while trying to convert the column \"tot_arm_entries_OB\". Fall back to string conversion. The error is: Conversion 'py2ri' not defined for objects of type '<class 'pandas.core.series.Series'>'\n",
      "  (name, str(e)))\n",
      "/Users/joshfeldman/Desktop/Projects/mice/venv/lib/python3.6/site-packages/rpy2/robjects/pandas2ri.py:67: UserWarning: Error while trying to convert the column \"tot_arm_entries_OT\". Fall back to string conversion. The error is: Conversion 'py2ri' not defined for objects of type '<class 'pandas.core.series.Series'>'\n",
      "  (name, str(e)))\n",
      "/Users/joshfeldman/Desktop/Projects/mice/venv/lib/python3.6/site-packages/rpy2/robjects/pandas2ri.py:67: UserWarning: Error while trying to convert the column \"total_distance_CL\". Fall back to string conversion. The error is: Conversion 'py2ri' not defined for objects of type '<class 'pandas.core.series.Series'>'\n",
      "  (name, str(e)))\n",
      "/Users/joshfeldman/Desktop/Projects/mice/venv/lib/python3.6/site-packages/rpy2/robjects/pandas2ri.py:67: UserWarning: Error while trying to convert the column \"total_distance_CR\". Fall back to string conversion. The error is: Conversion 'py2ri' not defined for objects of type '<class 'pandas.core.series.Series'>'\n",
      "  (name, str(e)))\n",
      "/Users/joshfeldman/Desktop/Projects/mice/venv/lib/python3.6/site-packages/rpy2/robjects/pandas2ri.py:67: UserWarning: Error while trying to convert the column \"total_distance_F1\". Fall back to string conversion. The error is: Conversion 'py2ri' not defined for objects of type '<class 'pandas.core.series.Series'>'\n",
      "  (name, str(e)))\n",
      "/Users/joshfeldman/Desktop/Projects/mice/venv/lib/python3.6/site-packages/rpy2/robjects/pandas2ri.py:67: UserWarning: Error while trying to convert the column \"total_distance_F2\". Fall back to string conversion. The error is: Conversion 'py2ri' not defined for objects of type '<class 'pandas.core.series.Series'>'\n",
      "  (name, str(e)))\n",
      "/Users/joshfeldman/Desktop/Projects/mice/venv/lib/python3.6/site-packages/rpy2/robjects/pandas2ri.py:67: UserWarning: Error while trying to convert the column \"total_distance_F3\". Fall back to string conversion. The error is: Conversion 'py2ri' not defined for objects of type '<class 'pandas.core.series.Series'>'\n",
      "  (name, str(e)))\n",
      "/Users/joshfeldman/Desktop/Projects/mice/venv/lib/python3.6/site-packages/rpy2/robjects/pandas2ri.py:67: UserWarning: Error while trying to convert the column \"total_distance_F4\". Fall back to string conversion. The error is: Conversion 'py2ri' not defined for objects of type '<class 'pandas.core.series.Series'>'\n",
      "  (name, str(e)))\n",
      "/Users/joshfeldman/Desktop/Projects/mice/venv/lib/python3.6/site-packages/rpy2/robjects/pandas2ri.py:67: UserWarning: Error while trying to convert the column \"total_distance_M\". Fall back to string conversion. The error is: Conversion 'py2ri' not defined for objects of type '<class 'pandas.core.series.Series'>'\n",
      "  (name, str(e)))\n",
      "/Users/joshfeldman/Desktop/Projects/mice/venv/lib/python3.6/site-packages/rpy2/robjects/pandas2ri.py:67: UserWarning: Error while trying to convert the column \"total_distance_OB\". Fall back to string conversion. The error is: Conversion 'py2ri' not defined for objects of type '<class 'pandas.core.series.Series'>'\n",
      "  (name, str(e)))\n",
      "/Users/joshfeldman/Desktop/Projects/mice/venv/lib/python3.6/site-packages/rpy2/robjects/pandas2ri.py:67: UserWarning: Error while trying to convert the column \"total_distance_OT\". Fall back to string conversion. The error is: Conversion 'py2ri' not defined for objects of type '<class 'pandas.core.series.Series'>'\n",
      "  (name, str(e)))\n",
      "/Users/joshfeldman/Desktop/Projects/mice/venv/lib/python3.6/site-packages/rpy2/robjects/pandas2ri.py:67: UserWarning: Error while trying to convert the column \"total_distance_closed\". Fall back to string conversion. The error is: Conversion 'py2ri' not defined for objects of type '<class 'pandas.core.series.Series'>'\n",
      "  (name, str(e)))\n",
      "/Users/joshfeldman/Desktop/Projects/mice/venv/lib/python3.6/site-packages/rpy2/robjects/pandas2ri.py:67: UserWarning: Error while trying to convert the column \"total_distance_open\". Fall back to string conversion. The error is: Conversion 'py2ri' not defined for objects of type '<class 'pandas.core.series.Series'>'\n",
      "  (name, str(e)))\n",
      "/Users/joshfeldman/Desktop/Projects/mice/venv/lib/python3.6/site-packages/rpy2/robjects/pandas2ri.py:67: UserWarning: Error while trying to convert the column \"turning_preferences_fraction_back\". Fall back to string conversion. The error is: Conversion 'py2ri' not defined for objects of type '<class 'pandas.core.series.Series'>'\n",
      "  (name, str(e)))\n",
      "/Users/joshfeldman/Desktop/Projects/mice/venv/lib/python3.6/site-packages/rpy2/robjects/pandas2ri.py:67: UserWarning: Error while trying to convert the column \"turning_preferences_fraction_back_into_closed\". Fall back to string conversion. The error is: Conversion 'py2ri' not defined for objects of type '<class 'pandas.core.series.Series'>'\n",
      "  (name, str(e)))\n",
      "/Users/joshfeldman/Desktop/Projects/mice/venv/lib/python3.6/site-packages/rpy2/robjects/pandas2ri.py:67: UserWarning: Error while trying to convert the column \"turning_preferences_fraction_back_into_open\". Fall back to string conversion. The error is: Conversion 'py2ri' not defined for objects of type '<class 'pandas.core.series.Series'>'\n",
      "  (name, str(e)))\n",
      "/Users/joshfeldman/Desktop/Projects/mice/venv/lib/python3.6/site-packages/rpy2/robjects/pandas2ri.py:67: UserWarning: Error while trying to convert the column \"turning_preferences_fraction_back_only_straight_back\". Fall back to string conversion. The error is: Conversion 'py2ri' not defined for objects of type '<class 'pandas.core.series.Series'>'\n",
      "  (name, str(e)))\n",
      "/Users/joshfeldman/Desktop/Projects/mice/venv/lib/python3.6/site-packages/rpy2/robjects/pandas2ri.py:67: UserWarning: Error while trying to convert the column \"turning_preferences_fraction_back_only_straight_back_into_closed\". Fall back to string conversion. The error is: Conversion 'py2ri' not defined for objects of type '<class 'pandas.core.series.Series'>'\n",
      "  (name, str(e)))\n",
      "/Users/joshfeldman/Desktop/Projects/mice/venv/lib/python3.6/site-packages/rpy2/robjects/pandas2ri.py:67: UserWarning: Error while trying to convert the column \"turning_preferences_fraction_back_only_straight_back_into_open\". Fall back to string conversion. The error is: Conversion 'py2ri' not defined for objects of type '<class 'pandas.core.series.Series'>'\n",
      "  (name, str(e)))\n",
      "/Users/joshfeldman/Desktop/Projects/mice/venv/lib/python3.6/site-packages/rpy2/robjects/pandas2ri.py:67: UserWarning: Error while trying to convert the column \"turning_preferences_fraction_left\". Fall back to string conversion. The error is: Conversion 'py2ri' not defined for objects of type '<class 'pandas.core.series.Series'>'\n",
      "  (name, str(e)))\n",
      "/Users/joshfeldman/Desktop/Projects/mice/venv/lib/python3.6/site-packages/rpy2/robjects/pandas2ri.py:67: UserWarning: Error while trying to convert the column \"turning_preferences_fraction_left_into_closed\". Fall back to string conversion. The error is: Conversion 'py2ri' not defined for objects of type '<class 'pandas.core.series.Series'>'\n",
      "  (name, str(e)))\n",
      "/Users/joshfeldman/Desktop/Projects/mice/venv/lib/python3.6/site-packages/rpy2/robjects/pandas2ri.py:67: UserWarning: Error while trying to convert the column \"turning_preferences_fraction_left_into_open\". Fall back to string conversion. The error is: Conversion 'py2ri' not defined for objects of type '<class 'pandas.core.series.Series'>'\n",
      "  (name, str(e)))\n",
      "/Users/joshfeldman/Desktop/Projects/mice/venv/lib/python3.6/site-packages/rpy2/robjects/pandas2ri.py:67: UserWarning: Error while trying to convert the column \"turning_preferences_fraction_left_only_right_left\". Fall back to string conversion. The error is: Conversion 'py2ri' not defined for objects of type '<class 'pandas.core.series.Series'>'\n",
      "  (name, str(e)))\n",
      "/Users/joshfeldman/Desktop/Projects/mice/venv/lib/python3.6/site-packages/rpy2/robjects/pandas2ri.py:67: UserWarning: Error while trying to convert the column \"turning_preferences_fraction_left_only_right_left_into_closed\". Fall back to string conversion. The error is: Conversion 'py2ri' not defined for objects of type '<class 'pandas.core.series.Series'>'\n",
      "  (name, str(e)))\n",
      "/Users/joshfeldman/Desktop/Projects/mice/venv/lib/python3.6/site-packages/rpy2/robjects/pandas2ri.py:67: UserWarning: Error while trying to convert the column \"turning_preferences_fraction_left_only_right_left_into_open\". Fall back to string conversion. The error is: Conversion 'py2ri' not defined for objects of type '<class 'pandas.core.series.Series'>'\n",
      "  (name, str(e)))\n",
      "/Users/joshfeldman/Desktop/Projects/mice/venv/lib/python3.6/site-packages/rpy2/robjects/pandas2ri.py:67: UserWarning: Error while trying to convert the column \"turning_preferences_fraction_right\". Fall back to string conversion. The error is: Conversion 'py2ri' not defined for objects of type '<class 'pandas.core.series.Series'>'\n",
      "  (name, str(e)))\n",
      "/Users/joshfeldman/Desktop/Projects/mice/venv/lib/python3.6/site-packages/rpy2/robjects/pandas2ri.py:67: UserWarning: Error while trying to convert the column \"turning_preferences_fraction_right_into_closed\". Fall back to string conversion. The error is: Conversion 'py2ri' not defined for objects of type '<class 'pandas.core.series.Series'>'\n",
      "  (name, str(e)))\n",
      "/Users/joshfeldman/Desktop/Projects/mice/venv/lib/python3.6/site-packages/rpy2/robjects/pandas2ri.py:67: UserWarning: Error while trying to convert the column \"turning_preferences_fraction_right_into_open\". Fall back to string conversion. The error is: Conversion 'py2ri' not defined for objects of type '<class 'pandas.core.series.Series'>'\n",
      "  (name, str(e)))\n",
      "/Users/joshfeldman/Desktop/Projects/mice/venv/lib/python3.6/site-packages/rpy2/robjects/pandas2ri.py:67: UserWarning: Error while trying to convert the column \"turning_preferences_fraction_right_only_right_left\". Fall back to string conversion. The error is: Conversion 'py2ri' not defined for objects of type '<class 'pandas.core.series.Series'>'\n",
      "  (name, str(e)))\n",
      "/Users/joshfeldman/Desktop/Projects/mice/venv/lib/python3.6/site-packages/rpy2/robjects/pandas2ri.py:67: UserWarning: Error while trying to convert the column \"turning_preferences_fraction_right_only_right_left_into_closed\". Fall back to string conversion. The error is: Conversion 'py2ri' not defined for objects of type '<class 'pandas.core.series.Series'>'\n",
      "  (name, str(e)))\n",
      "/Users/joshfeldman/Desktop/Projects/mice/venv/lib/python3.6/site-packages/rpy2/robjects/pandas2ri.py:67: UserWarning: Error while trying to convert the column \"turning_preferences_fraction_right_only_right_left_into_open\". Fall back to string conversion. The error is: Conversion 'py2ri' not defined for objects of type '<class 'pandas.core.series.Series'>'\n",
      "  (name, str(e)))\n",
      "/Users/joshfeldman/Desktop/Projects/mice/venv/lib/python3.6/site-packages/rpy2/robjects/pandas2ri.py:67: UserWarning: Error while trying to convert the column \"turning_preferences_fraction_straight\". Fall back to string conversion. The error is: Conversion 'py2ri' not defined for objects of type '<class 'pandas.core.series.Series'>'\n",
      "  (name, str(e)))\n",
      "/Users/joshfeldman/Desktop/Projects/mice/venv/lib/python3.6/site-packages/rpy2/robjects/pandas2ri.py:67: UserWarning: Error while trying to convert the column \"turning_preferences_fraction_straight_into_closed\". Fall back to string conversion. The error is: Conversion 'py2ri' not defined for objects of type '<class 'pandas.core.series.Series'>'\n",
      "  (name, str(e)))\n",
      "/Users/joshfeldman/Desktop/Projects/mice/venv/lib/python3.6/site-packages/rpy2/robjects/pandas2ri.py:67: UserWarning: Error while trying to convert the column \"turning_preferences_fraction_straight_into_open\". Fall back to string conversion. The error is: Conversion 'py2ri' not defined for objects of type '<class 'pandas.core.series.Series'>'\n",
      "  (name, str(e)))\n",
      "/Users/joshfeldman/Desktop/Projects/mice/venv/lib/python3.6/site-packages/rpy2/robjects/pandas2ri.py:67: UserWarning: Error while trying to convert the column \"turning_preferences_fraction_straight_only_straight_back\". Fall back to string conversion. The error is: Conversion 'py2ri' not defined for objects of type '<class 'pandas.core.series.Series'>'\n",
      "  (name, str(e)))\n",
      "/Users/joshfeldman/Desktop/Projects/mice/venv/lib/python3.6/site-packages/rpy2/robjects/pandas2ri.py:67: UserWarning: Error while trying to convert the column \"turning_preferences_fraction_straight_only_straight_back_into_closed\". Fall back to string conversion. The error is: Conversion 'py2ri' not defined for objects of type '<class 'pandas.core.series.Series'>'\n",
      "  (name, str(e)))\n",
      "/Users/joshfeldman/Desktop/Projects/mice/venv/lib/python3.6/site-packages/rpy2/robjects/pandas2ri.py:67: UserWarning: Error while trying to convert the column \"turning_preferences_fraction_straight_only_straight_back_into_open\". Fall back to string conversion. The error is: Conversion 'py2ri' not defined for objects of type '<class 'pandas.core.series.Series'>'\n",
      "  (name, str(e)))\n",
      "/Users/joshfeldman/Desktop/Projects/mice/venv/lib/python3.6/site-packages/rpy2/robjects/pandas2ri.py:67: UserWarning: Error while trying to convert the column \"turning_preferences_num_total\". Fall back to string conversion. The error is: Conversion 'py2ri' not defined for objects of type '<class 'pandas.core.series.Series'>'\n",
      "  (name, str(e)))\n",
      "/Users/joshfeldman/Desktop/Projects/mice/venv/lib/python3.6/site-packages/rpy2/robjects/pandas2ri.py:67: UserWarning: Error while trying to convert the column \"turning_preferences_num_total_into_closed\". Fall back to string conversion. The error is: Conversion 'py2ri' not defined for objects of type '<class 'pandas.core.series.Series'>'\n",
      "  (name, str(e)))\n",
      "/Users/joshfeldman/Desktop/Projects/mice/venv/lib/python3.6/site-packages/rpy2/robjects/pandas2ri.py:67: UserWarning: Error while trying to convert the column \"turning_preferences_num_total_into_open\". Fall back to string conversion. The error is: Conversion 'py2ri' not defined for objects of type '<class 'pandas.core.series.Series'>'\n",
      "  (name, str(e)))\n",
      "/Users/joshfeldman/Desktop/Projects/mice/venv/lib/python3.6/site-packages/rpy2/robjects/pandas2ri.py:67: UserWarning: Error while trying to convert the column \"velocity_CL_down_average_speed\". Fall back to string conversion. The error is: Conversion 'py2ri' not defined for objects of type '<class 'pandas.core.series.Series'>'\n",
      "  (name, str(e)))\n",
      "/Users/joshfeldman/Desktop/Projects/mice/venv/lib/python3.6/site-packages/rpy2/robjects/pandas2ri.py:67: UserWarning: Error while trying to convert the column \"velocity_CL_down_average_speed_active\". Fall back to string conversion. The error is: Conversion 'py2ri' not defined for objects of type '<class 'pandas.core.series.Series'>'\n",
      "  (name, str(e)))\n",
      "/Users/joshfeldman/Desktop/Projects/mice/venv/lib/python3.6/site-packages/rpy2/robjects/pandas2ri.py:67: UserWarning: Error while trying to convert the column \"velocity_CL_down_median_speed\". Fall back to string conversion. The error is: Conversion 'py2ri' not defined for objects of type '<class 'pandas.core.series.Series'>'\n",
      "  (name, str(e)))\n",
      "/Users/joshfeldman/Desktop/Projects/mice/venv/lib/python3.6/site-packages/rpy2/robjects/pandas2ri.py:67: UserWarning: Error while trying to convert the column \"velocity_CL_down_median_speed_active\". Fall back to string conversion. The error is: Conversion 'py2ri' not defined for objects of type '<class 'pandas.core.series.Series'>'\n",
      "  (name, str(e)))\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/Users/joshfeldman/Desktop/Projects/mice/venv/lib/python3.6/site-packages/rpy2/robjects/pandas2ri.py:67: UserWarning: Error while trying to convert the column \"velocity_CL_left_average_speed\". Fall back to string conversion. The error is: Conversion 'py2ri' not defined for objects of type '<class 'pandas.core.series.Series'>'\n",
      "  (name, str(e)))\n",
      "/Users/joshfeldman/Desktop/Projects/mice/venv/lib/python3.6/site-packages/rpy2/robjects/pandas2ri.py:67: UserWarning: Error while trying to convert the column \"velocity_CL_left_average_speed_active\". Fall back to string conversion. The error is: Conversion 'py2ri' not defined for objects of type '<class 'pandas.core.series.Series'>'\n",
      "  (name, str(e)))\n",
      "/Users/joshfeldman/Desktop/Projects/mice/venv/lib/python3.6/site-packages/rpy2/robjects/pandas2ri.py:67: UserWarning: Error while trying to convert the column \"velocity_CL_left_median_speed\". Fall back to string conversion. The error is: Conversion 'py2ri' not defined for objects of type '<class 'pandas.core.series.Series'>'\n",
      "  (name, str(e)))\n",
      "/Users/joshfeldman/Desktop/Projects/mice/venv/lib/python3.6/site-packages/rpy2/robjects/pandas2ri.py:67: UserWarning: Error while trying to convert the column \"velocity_CL_left_median_speed_active\". Fall back to string conversion. The error is: Conversion 'py2ri' not defined for objects of type '<class 'pandas.core.series.Series'>'\n",
      "  (name, str(e)))\n",
      "/Users/joshfeldman/Desktop/Projects/mice/venv/lib/python3.6/site-packages/rpy2/robjects/pandas2ri.py:67: UserWarning: Error while trying to convert the column \"velocity_CL_right_average_speed\". Fall back to string conversion. The error is: Conversion 'py2ri' not defined for objects of type '<class 'pandas.core.series.Series'>'\n",
      "  (name, str(e)))\n",
      "/Users/joshfeldman/Desktop/Projects/mice/venv/lib/python3.6/site-packages/rpy2/robjects/pandas2ri.py:67: UserWarning: Error while trying to convert the column \"velocity_CL_right_average_speed_active\". Fall back to string conversion. The error is: Conversion 'py2ri' not defined for objects of type '<class 'pandas.core.series.Series'>'\n",
      "  (name, str(e)))\n",
      "/Users/joshfeldman/Desktop/Projects/mice/venv/lib/python3.6/site-packages/rpy2/robjects/pandas2ri.py:67: UserWarning: Error while trying to convert the column \"velocity_CL_right_median_speed\". Fall back to string conversion. The error is: Conversion 'py2ri' not defined for objects of type '<class 'pandas.core.series.Series'>'\n",
      "  (name, str(e)))\n",
      "/Users/joshfeldman/Desktop/Projects/mice/venv/lib/python3.6/site-packages/rpy2/robjects/pandas2ri.py:67: UserWarning: Error while trying to convert the column \"velocity_CL_right_median_speed_active\". Fall back to string conversion. The error is: Conversion 'py2ri' not defined for objects of type '<class 'pandas.core.series.Series'>'\n",
      "  (name, str(e)))\n",
      "/Users/joshfeldman/Desktop/Projects/mice/venv/lib/python3.6/site-packages/rpy2/robjects/pandas2ri.py:67: UserWarning: Error while trying to convert the column \"velocity_CL_total_average_speed\". Fall back to string conversion. The error is: Conversion 'py2ri' not defined for objects of type '<class 'pandas.core.series.Series'>'\n",
      "  (name, str(e)))\n",
      "/Users/joshfeldman/Desktop/Projects/mice/venv/lib/python3.6/site-packages/rpy2/robjects/pandas2ri.py:67: UserWarning: Error while trying to convert the column \"velocity_CL_total_average_speed_active\". Fall back to string conversion. The error is: Conversion 'py2ri' not defined for objects of type '<class 'pandas.core.series.Series'>'\n",
      "  (name, str(e)))\n",
      "/Users/joshfeldman/Desktop/Projects/mice/venv/lib/python3.6/site-packages/rpy2/robjects/pandas2ri.py:67: UserWarning: Error while trying to convert the column \"velocity_CL_total_median_speed\". Fall back to string conversion. The error is: Conversion 'py2ri' not defined for objects of type '<class 'pandas.core.series.Series'>'\n",
      "  (name, str(e)))\n",
      "/Users/joshfeldman/Desktop/Projects/mice/venv/lib/python3.6/site-packages/rpy2/robjects/pandas2ri.py:67: UserWarning: Error while trying to convert the column \"velocity_CL_total_median_speed_active\". Fall back to string conversion. The error is: Conversion 'py2ri' not defined for objects of type '<class 'pandas.core.series.Series'>'\n",
      "  (name, str(e)))\n",
      "/Users/joshfeldman/Desktop/Projects/mice/venv/lib/python3.6/site-packages/rpy2/robjects/pandas2ri.py:67: UserWarning: Error while trying to convert the column \"velocity_CL_up_average_speed\". Fall back to string conversion. The error is: Conversion 'py2ri' not defined for objects of type '<class 'pandas.core.series.Series'>'\n",
      "  (name, str(e)))\n",
      "/Users/joshfeldman/Desktop/Projects/mice/venv/lib/python3.6/site-packages/rpy2/robjects/pandas2ri.py:67: UserWarning: Error while trying to convert the column \"velocity_CL_up_average_speed_active\". Fall back to string conversion. The error is: Conversion 'py2ri' not defined for objects of type '<class 'pandas.core.series.Series'>'\n",
      "  (name, str(e)))\n",
      "/Users/joshfeldman/Desktop/Projects/mice/venv/lib/python3.6/site-packages/rpy2/robjects/pandas2ri.py:67: UserWarning: Error while trying to convert the column \"velocity_CL_up_median_speed\". Fall back to string conversion. The error is: Conversion 'py2ri' not defined for objects of type '<class 'pandas.core.series.Series'>'\n",
      "  (name, str(e)))\n",
      "/Users/joshfeldman/Desktop/Projects/mice/venv/lib/python3.6/site-packages/rpy2/robjects/pandas2ri.py:67: UserWarning: Error while trying to convert the column \"velocity_CL_up_median_speed_active\". Fall back to string conversion. The error is: Conversion 'py2ri' not defined for objects of type '<class 'pandas.core.series.Series'>'\n",
      "  (name, str(e)))\n",
      "/Users/joshfeldman/Desktop/Projects/mice/venv/lib/python3.6/site-packages/rpy2/robjects/pandas2ri.py:67: UserWarning: Error while trying to convert the column \"velocity_CR_down_average_speed\". Fall back to string conversion. The error is: Conversion 'py2ri' not defined for objects of type '<class 'pandas.core.series.Series'>'\n",
      "  (name, str(e)))\n",
      "/Users/joshfeldman/Desktop/Projects/mice/venv/lib/python3.6/site-packages/rpy2/robjects/pandas2ri.py:67: UserWarning: Error while trying to convert the column \"velocity_CR_down_average_speed_active\". Fall back to string conversion. The error is: Conversion 'py2ri' not defined for objects of type '<class 'pandas.core.series.Series'>'\n",
      "  (name, str(e)))\n",
      "/Users/joshfeldman/Desktop/Projects/mice/venv/lib/python3.6/site-packages/rpy2/robjects/pandas2ri.py:67: UserWarning: Error while trying to convert the column \"velocity_CR_down_median_speed\". Fall back to string conversion. The error is: Conversion 'py2ri' not defined for objects of type '<class 'pandas.core.series.Series'>'\n",
      "  (name, str(e)))\n",
      "/Users/joshfeldman/Desktop/Projects/mice/venv/lib/python3.6/site-packages/rpy2/robjects/pandas2ri.py:67: UserWarning: Error while trying to convert the column \"velocity_CR_down_median_speed_active\". Fall back to string conversion. The error is: Conversion 'py2ri' not defined for objects of type '<class 'pandas.core.series.Series'>'\n",
      "  (name, str(e)))\n",
      "/Users/joshfeldman/Desktop/Projects/mice/venv/lib/python3.6/site-packages/rpy2/robjects/pandas2ri.py:67: UserWarning: Error while trying to convert the column \"velocity_CR_left_average_speed\". Fall back to string conversion. The error is: Conversion 'py2ri' not defined for objects of type '<class 'pandas.core.series.Series'>'\n",
      "  (name, str(e)))\n",
      "/Users/joshfeldman/Desktop/Projects/mice/venv/lib/python3.6/site-packages/rpy2/robjects/pandas2ri.py:67: UserWarning: Error while trying to convert the column \"velocity_CR_left_average_speed_active\". Fall back to string conversion. The error is: Conversion 'py2ri' not defined for objects of type '<class 'pandas.core.series.Series'>'\n",
      "  (name, str(e)))\n",
      "/Users/joshfeldman/Desktop/Projects/mice/venv/lib/python3.6/site-packages/rpy2/robjects/pandas2ri.py:67: UserWarning: Error while trying to convert the column \"velocity_CR_left_median_speed\". Fall back to string conversion. The error is: Conversion 'py2ri' not defined for objects of type '<class 'pandas.core.series.Series'>'\n",
      "  (name, str(e)))\n",
      "/Users/joshfeldman/Desktop/Projects/mice/venv/lib/python3.6/site-packages/rpy2/robjects/pandas2ri.py:67: UserWarning: Error while trying to convert the column \"velocity_CR_left_median_speed_active\". Fall back to string conversion. The error is: Conversion 'py2ri' not defined for objects of type '<class 'pandas.core.series.Series'>'\n",
      "  (name, str(e)))\n",
      "/Users/joshfeldman/Desktop/Projects/mice/venv/lib/python3.6/site-packages/rpy2/robjects/pandas2ri.py:67: UserWarning: Error while trying to convert the column \"velocity_CR_right_average_speed\". Fall back to string conversion. The error is: Conversion 'py2ri' not defined for objects of type '<class 'pandas.core.series.Series'>'\n",
      "  (name, str(e)))\n",
      "/Users/joshfeldman/Desktop/Projects/mice/venv/lib/python3.6/site-packages/rpy2/robjects/pandas2ri.py:67: UserWarning: Error while trying to convert the column \"velocity_CR_right_average_speed_active\". Fall back to string conversion. The error is: Conversion 'py2ri' not defined for objects of type '<class 'pandas.core.series.Series'>'\n",
      "  (name, str(e)))\n",
      "/Users/joshfeldman/Desktop/Projects/mice/venv/lib/python3.6/site-packages/rpy2/robjects/pandas2ri.py:67: UserWarning: Error while trying to convert the column \"velocity_CR_right_median_speed\". Fall back to string conversion. The error is: Conversion 'py2ri' not defined for objects of type '<class 'pandas.core.series.Series'>'\n",
      "  (name, str(e)))\n",
      "/Users/joshfeldman/Desktop/Projects/mice/venv/lib/python3.6/site-packages/rpy2/robjects/pandas2ri.py:67: UserWarning: Error while trying to convert the column \"velocity_CR_right_median_speed_active\". Fall back to string conversion. The error is: Conversion 'py2ri' not defined for objects of type '<class 'pandas.core.series.Series'>'\n",
      "  (name, str(e)))\n",
      "/Users/joshfeldman/Desktop/Projects/mice/venv/lib/python3.6/site-packages/rpy2/robjects/pandas2ri.py:67: UserWarning: Error while trying to convert the column \"velocity_CR_total_average_speed\". Fall back to string conversion. The error is: Conversion 'py2ri' not defined for objects of type '<class 'pandas.core.series.Series'>'\n",
      "  (name, str(e)))\n",
      "/Users/joshfeldman/Desktop/Projects/mice/venv/lib/python3.6/site-packages/rpy2/robjects/pandas2ri.py:67: UserWarning: Error while trying to convert the column \"velocity_CR_total_average_speed_active\". Fall back to string conversion. The error is: Conversion 'py2ri' not defined for objects of type '<class 'pandas.core.series.Series'>'\n",
      "  (name, str(e)))\n",
      "/Users/joshfeldman/Desktop/Projects/mice/venv/lib/python3.6/site-packages/rpy2/robjects/pandas2ri.py:67: UserWarning: Error while trying to convert the column \"velocity_CR_total_median_speed\". Fall back to string conversion. The error is: Conversion 'py2ri' not defined for objects of type '<class 'pandas.core.series.Series'>'\n",
      "  (name, str(e)))\n",
      "/Users/joshfeldman/Desktop/Projects/mice/venv/lib/python3.6/site-packages/rpy2/robjects/pandas2ri.py:67: UserWarning: Error while trying to convert the column \"velocity_CR_total_median_speed_active\". Fall back to string conversion. The error is: Conversion 'py2ri' not defined for objects of type '<class 'pandas.core.series.Series'>'\n",
      "  (name, str(e)))\n",
      "/Users/joshfeldman/Desktop/Projects/mice/venv/lib/python3.6/site-packages/rpy2/robjects/pandas2ri.py:67: UserWarning: Error while trying to convert the column \"velocity_CR_up_average_speed\". Fall back to string conversion. The error is: Conversion 'py2ri' not defined for objects of type '<class 'pandas.core.series.Series'>'\n",
      "  (name, str(e)))\n",
      "/Users/joshfeldman/Desktop/Projects/mice/venv/lib/python3.6/site-packages/rpy2/robjects/pandas2ri.py:67: UserWarning: Error while trying to convert the column \"velocity_CR_up_average_speed_active\". Fall back to string conversion. The error is: Conversion 'py2ri' not defined for objects of type '<class 'pandas.core.series.Series'>'\n",
      "  (name, str(e)))\n",
      "/Users/joshfeldman/Desktop/Projects/mice/venv/lib/python3.6/site-packages/rpy2/robjects/pandas2ri.py:67: UserWarning: Error while trying to convert the column \"velocity_CR_up_median_speed\". Fall back to string conversion. The error is: Conversion 'py2ri' not defined for objects of type '<class 'pandas.core.series.Series'>'\n",
      "  (name, str(e)))\n",
      "/Users/joshfeldman/Desktop/Projects/mice/venv/lib/python3.6/site-packages/rpy2/robjects/pandas2ri.py:67: UserWarning: Error while trying to convert the column \"velocity_CR_up_median_speed_active\". Fall back to string conversion. The error is: Conversion 'py2ri' not defined for objects of type '<class 'pandas.core.series.Series'>'\n",
      "  (name, str(e)))\n",
      "/Users/joshfeldman/Desktop/Projects/mice/venv/lib/python3.6/site-packages/rpy2/robjects/pandas2ri.py:67: UserWarning: Error while trying to convert the column \"velocity_M_down_average_speed\". Fall back to string conversion. The error is: Conversion 'py2ri' not defined for objects of type '<class 'pandas.core.series.Series'>'\n",
      "  (name, str(e)))\n",
      "/Users/joshfeldman/Desktop/Projects/mice/venv/lib/python3.6/site-packages/rpy2/robjects/pandas2ri.py:67: UserWarning: Error while trying to convert the column \"velocity_M_down_average_speed_active\". Fall back to string conversion. The error is: Conversion 'py2ri' not defined for objects of type '<class 'pandas.core.series.Series'>'\n",
      "  (name, str(e)))\n",
      "/Users/joshfeldman/Desktop/Projects/mice/venv/lib/python3.6/site-packages/rpy2/robjects/pandas2ri.py:67: UserWarning: Error while trying to convert the column \"velocity_M_down_median_speed\". Fall back to string conversion. The error is: Conversion 'py2ri' not defined for objects of type '<class 'pandas.core.series.Series'>'\n",
      "  (name, str(e)))\n",
      "/Users/joshfeldman/Desktop/Projects/mice/venv/lib/python3.6/site-packages/rpy2/robjects/pandas2ri.py:67: UserWarning: Error while trying to convert the column \"velocity_M_down_median_speed_active\". Fall back to string conversion. The error is: Conversion 'py2ri' not defined for objects of type '<class 'pandas.core.series.Series'>'\n",
      "  (name, str(e)))\n",
      "/Users/joshfeldman/Desktop/Projects/mice/venv/lib/python3.6/site-packages/rpy2/robjects/pandas2ri.py:67: UserWarning: Error while trying to convert the column \"velocity_M_left_average_speed\". Fall back to string conversion. The error is: Conversion 'py2ri' not defined for objects of type '<class 'pandas.core.series.Series'>'\n",
      "  (name, str(e)))\n",
      "/Users/joshfeldman/Desktop/Projects/mice/venv/lib/python3.6/site-packages/rpy2/robjects/pandas2ri.py:67: UserWarning: Error while trying to convert the column \"velocity_M_left_average_speed_active\". Fall back to string conversion. The error is: Conversion 'py2ri' not defined for objects of type '<class 'pandas.core.series.Series'>'\n",
      "  (name, str(e)))\n",
      "/Users/joshfeldman/Desktop/Projects/mice/venv/lib/python3.6/site-packages/rpy2/robjects/pandas2ri.py:67: UserWarning: Error while trying to convert the column \"velocity_M_left_median_speed\". Fall back to string conversion. The error is: Conversion 'py2ri' not defined for objects of type '<class 'pandas.core.series.Series'>'\n",
      "  (name, str(e)))\n",
      "/Users/joshfeldman/Desktop/Projects/mice/venv/lib/python3.6/site-packages/rpy2/robjects/pandas2ri.py:67: UserWarning: Error while trying to convert the column \"velocity_M_left_median_speed_active\". Fall back to string conversion. The error is: Conversion 'py2ri' not defined for objects of type '<class 'pandas.core.series.Series'>'\n",
      "  (name, str(e)))\n",
      "/Users/joshfeldman/Desktop/Projects/mice/venv/lib/python3.6/site-packages/rpy2/robjects/pandas2ri.py:67: UserWarning: Error while trying to convert the column \"velocity_M_right_average_speed\". Fall back to string conversion. The error is: Conversion 'py2ri' not defined for objects of type '<class 'pandas.core.series.Series'>'\n",
      "  (name, str(e)))\n",
      "/Users/joshfeldman/Desktop/Projects/mice/venv/lib/python3.6/site-packages/rpy2/robjects/pandas2ri.py:67: UserWarning: Error while trying to convert the column \"velocity_M_right_average_speed_active\". Fall back to string conversion. The error is: Conversion 'py2ri' not defined for objects of type '<class 'pandas.core.series.Series'>'\n",
      "  (name, str(e)))\n",
      "/Users/joshfeldman/Desktop/Projects/mice/venv/lib/python3.6/site-packages/rpy2/robjects/pandas2ri.py:67: UserWarning: Error while trying to convert the column \"velocity_M_right_median_speed\". Fall back to string conversion. The error is: Conversion 'py2ri' not defined for objects of type '<class 'pandas.core.series.Series'>'\n",
      "  (name, str(e)))\n",
      "/Users/joshfeldman/Desktop/Projects/mice/venv/lib/python3.6/site-packages/rpy2/robjects/pandas2ri.py:67: UserWarning: Error while trying to convert the column \"velocity_M_right_median_speed_active\". Fall back to string conversion. The error is: Conversion 'py2ri' not defined for objects of type '<class 'pandas.core.series.Series'>'\n",
      "  (name, str(e)))\n",
      "/Users/joshfeldman/Desktop/Projects/mice/venv/lib/python3.6/site-packages/rpy2/robjects/pandas2ri.py:67: UserWarning: Error while trying to convert the column \"velocity_M_total_average_speed\". Fall back to string conversion. The error is: Conversion 'py2ri' not defined for objects of type '<class 'pandas.core.series.Series'>'\n",
      "  (name, str(e)))\n",
      "/Users/joshfeldman/Desktop/Projects/mice/venv/lib/python3.6/site-packages/rpy2/robjects/pandas2ri.py:67: UserWarning: Error while trying to convert the column \"velocity_M_total_average_speed_active\". Fall back to string conversion. The error is: Conversion 'py2ri' not defined for objects of type '<class 'pandas.core.series.Series'>'\n",
      "  (name, str(e)))\n",
      "/Users/joshfeldman/Desktop/Projects/mice/venv/lib/python3.6/site-packages/rpy2/robjects/pandas2ri.py:67: UserWarning: Error while trying to convert the column \"velocity_M_total_median_speed\". Fall back to string conversion. The error is: Conversion 'py2ri' not defined for objects of type '<class 'pandas.core.series.Series'>'\n",
      "  (name, str(e)))\n",
      "/Users/joshfeldman/Desktop/Projects/mice/venv/lib/python3.6/site-packages/rpy2/robjects/pandas2ri.py:67: UserWarning: Error while trying to convert the column \"velocity_M_total_median_speed_active\". Fall back to string conversion. The error is: Conversion 'py2ri' not defined for objects of type '<class 'pandas.core.series.Series'>'\n",
      "  (name, str(e)))\n",
      "/Users/joshfeldman/Desktop/Projects/mice/venv/lib/python3.6/site-packages/rpy2/robjects/pandas2ri.py:67: UserWarning: Error while trying to convert the column \"velocity_M_up_average_speed\". Fall back to string conversion. The error is: Conversion 'py2ri' not defined for objects of type '<class 'pandas.core.series.Series'>'\n",
      "  (name, str(e)))\n",
      "/Users/joshfeldman/Desktop/Projects/mice/venv/lib/python3.6/site-packages/rpy2/robjects/pandas2ri.py:67: UserWarning: Error while trying to convert the column \"velocity_M_up_average_speed_active\". Fall back to string conversion. The error is: Conversion 'py2ri' not defined for objects of type '<class 'pandas.core.series.Series'>'\n",
      "  (name, str(e)))\n",
      "/Users/joshfeldman/Desktop/Projects/mice/venv/lib/python3.6/site-packages/rpy2/robjects/pandas2ri.py:67: UserWarning: Error while trying to convert the column \"velocity_M_up_median_speed\". Fall back to string conversion. The error is: Conversion 'py2ri' not defined for objects of type '<class 'pandas.core.series.Series'>'\n",
      "  (name, str(e)))\n",
      "/Users/joshfeldman/Desktop/Projects/mice/venv/lib/python3.6/site-packages/rpy2/robjects/pandas2ri.py:67: UserWarning: Error while trying to convert the column \"velocity_M_up_median_speed_active\". Fall back to string conversion. The error is: Conversion 'py2ri' not defined for objects of type '<class 'pandas.core.series.Series'>'\n",
      "  (name, str(e)))\n",
      "/Users/joshfeldman/Desktop/Projects/mice/venv/lib/python3.6/site-packages/rpy2/robjects/pandas2ri.py:67: UserWarning: Error while trying to convert the column \"velocity_OB_down_average_speed\". Fall back to string conversion. The error is: Conversion 'py2ri' not defined for objects of type '<class 'pandas.core.series.Series'>'\n",
      "  (name, str(e)))\n",
      "/Users/joshfeldman/Desktop/Projects/mice/venv/lib/python3.6/site-packages/rpy2/robjects/pandas2ri.py:67: UserWarning: Error while trying to convert the column \"velocity_OB_down_average_speed_active\". Fall back to string conversion. The error is: Conversion 'py2ri' not defined for objects of type '<class 'pandas.core.series.Series'>'\n",
      "  (name, str(e)))\n",
      "/Users/joshfeldman/Desktop/Projects/mice/venv/lib/python3.6/site-packages/rpy2/robjects/pandas2ri.py:67: UserWarning: Error while trying to convert the column \"velocity_OB_down_median_speed\". Fall back to string conversion. The error is: Conversion 'py2ri' not defined for objects of type '<class 'pandas.core.series.Series'>'\n",
      "  (name, str(e)))\n",
      "/Users/joshfeldman/Desktop/Projects/mice/venv/lib/python3.6/site-packages/rpy2/robjects/pandas2ri.py:67: UserWarning: Error while trying to convert the column \"velocity_OB_down_median_speed_active\". Fall back to string conversion. The error is: Conversion 'py2ri' not defined for objects of type '<class 'pandas.core.series.Series'>'\n",
      "  (name, str(e)))\n",
      "/Users/joshfeldman/Desktop/Projects/mice/venv/lib/python3.6/site-packages/rpy2/robjects/pandas2ri.py:67: UserWarning: Error while trying to convert the column \"velocity_OB_left_average_speed\". Fall back to string conversion. The error is: Conversion 'py2ri' not defined for objects of type '<class 'pandas.core.series.Series'>'\n",
      "  (name, str(e)))\n",
      "/Users/joshfeldman/Desktop/Projects/mice/venv/lib/python3.6/site-packages/rpy2/robjects/pandas2ri.py:67: UserWarning: Error while trying to convert the column \"velocity_OB_left_average_speed_active\". Fall back to string conversion. The error is: Conversion 'py2ri' not defined for objects of type '<class 'pandas.core.series.Series'>'\n",
      "  (name, str(e)))\n",
      "/Users/joshfeldman/Desktop/Projects/mice/venv/lib/python3.6/site-packages/rpy2/robjects/pandas2ri.py:67: UserWarning: Error while trying to convert the column \"velocity_OB_left_median_speed\". Fall back to string conversion. The error is: Conversion 'py2ri' not defined for objects of type '<class 'pandas.core.series.Series'>'\n",
      "  (name, str(e)))\n",
      "/Users/joshfeldman/Desktop/Projects/mice/venv/lib/python3.6/site-packages/rpy2/robjects/pandas2ri.py:67: UserWarning: Error while trying to convert the column \"velocity_OB_left_median_speed_active\". Fall back to string conversion. The error is: Conversion 'py2ri' not defined for objects of type '<class 'pandas.core.series.Series'>'\n",
      "  (name, str(e)))\n",
      "/Users/joshfeldman/Desktop/Projects/mice/venv/lib/python3.6/site-packages/rpy2/robjects/pandas2ri.py:67: UserWarning: Error while trying to convert the column \"velocity_OB_right_average_speed\". Fall back to string conversion. The error is: Conversion 'py2ri' not defined for objects of type '<class 'pandas.core.series.Series'>'\n",
      "  (name, str(e)))\n",
      "/Users/joshfeldman/Desktop/Projects/mice/venv/lib/python3.6/site-packages/rpy2/robjects/pandas2ri.py:67: UserWarning: Error while trying to convert the column \"velocity_OB_right_average_speed_active\". Fall back to string conversion. The error is: Conversion 'py2ri' not defined for objects of type '<class 'pandas.core.series.Series'>'\n",
      "  (name, str(e)))\n",
      "/Users/joshfeldman/Desktop/Projects/mice/venv/lib/python3.6/site-packages/rpy2/robjects/pandas2ri.py:67: UserWarning: Error while trying to convert the column \"velocity_OB_right_median_speed\". Fall back to string conversion. The error is: Conversion 'py2ri' not defined for objects of type '<class 'pandas.core.series.Series'>'\n",
      "  (name, str(e)))\n",
      "/Users/joshfeldman/Desktop/Projects/mice/venv/lib/python3.6/site-packages/rpy2/robjects/pandas2ri.py:67: UserWarning: Error while trying to convert the column \"velocity_OB_right_median_speed_active\". Fall back to string conversion. The error is: Conversion 'py2ri' not defined for objects of type '<class 'pandas.core.series.Series'>'\n",
      "  (name, str(e)))\n",
      "/Users/joshfeldman/Desktop/Projects/mice/venv/lib/python3.6/site-packages/rpy2/robjects/pandas2ri.py:67: UserWarning: Error while trying to convert the column \"velocity_OB_total_average_speed\". Fall back to string conversion. The error is: Conversion 'py2ri' not defined for objects of type '<class 'pandas.core.series.Series'>'\n",
      "  (name, str(e)))\n",
      "/Users/joshfeldman/Desktop/Projects/mice/venv/lib/python3.6/site-packages/rpy2/robjects/pandas2ri.py:67: UserWarning: Error while trying to convert the column \"velocity_OB_total_average_speed_active\". Fall back to string conversion. The error is: Conversion 'py2ri' not defined for objects of type '<class 'pandas.core.series.Series'>'\n",
      "  (name, str(e)))\n",
      "/Users/joshfeldman/Desktop/Projects/mice/venv/lib/python3.6/site-packages/rpy2/robjects/pandas2ri.py:67: UserWarning: Error while trying to convert the column \"velocity_OB_total_median_speed\". Fall back to string conversion. The error is: Conversion 'py2ri' not defined for objects of type '<class 'pandas.core.series.Series'>'\n",
      "  (name, str(e)))\n",
      "/Users/joshfeldman/Desktop/Projects/mice/venv/lib/python3.6/site-packages/rpy2/robjects/pandas2ri.py:67: UserWarning: Error while trying to convert the column \"velocity_OB_total_median_speed_active\". Fall back to string conversion. The error is: Conversion 'py2ri' not defined for objects of type '<class 'pandas.core.series.Series'>'\n",
      "  (name, str(e)))\n",
      "/Users/joshfeldman/Desktop/Projects/mice/venv/lib/python3.6/site-packages/rpy2/robjects/pandas2ri.py:67: UserWarning: Error while trying to convert the column \"velocity_OB_up_average_speed\". Fall back to string conversion. The error is: Conversion 'py2ri' not defined for objects of type '<class 'pandas.core.series.Series'>'\n",
      "  (name, str(e)))\n",
      "/Users/joshfeldman/Desktop/Projects/mice/venv/lib/python3.6/site-packages/rpy2/robjects/pandas2ri.py:67: UserWarning: Error while trying to convert the column \"velocity_OB_up_average_speed_active\". Fall back to string conversion. The error is: Conversion 'py2ri' not defined for objects of type '<class 'pandas.core.series.Series'>'\n",
      "  (name, str(e)))\n",
      "/Users/joshfeldman/Desktop/Projects/mice/venv/lib/python3.6/site-packages/rpy2/robjects/pandas2ri.py:67: UserWarning: Error while trying to convert the column \"velocity_OB_up_median_speed\". Fall back to string conversion. The error is: Conversion 'py2ri' not defined for objects of type '<class 'pandas.core.series.Series'>'\n",
      "  (name, str(e)))\n",
      "/Users/joshfeldman/Desktop/Projects/mice/venv/lib/python3.6/site-packages/rpy2/robjects/pandas2ri.py:67: UserWarning: Error while trying to convert the column \"velocity_OB_up_median_speed_active\". Fall back to string conversion. The error is: Conversion 'py2ri' not defined for objects of type '<class 'pandas.core.series.Series'>'\n",
      "  (name, str(e)))\n",
      "/Users/joshfeldman/Desktop/Projects/mice/venv/lib/python3.6/site-packages/rpy2/robjects/pandas2ri.py:67: UserWarning: Error while trying to convert the column \"velocity_OT_down_average_speed\". Fall back to string conversion. The error is: Conversion 'py2ri' not defined for objects of type '<class 'pandas.core.series.Series'>'\n",
      "  (name, str(e)))\n",
      "/Users/joshfeldman/Desktop/Projects/mice/venv/lib/python3.6/site-packages/rpy2/robjects/pandas2ri.py:67: UserWarning: Error while trying to convert the column \"velocity_OT_down_average_speed_active\". Fall back to string conversion. The error is: Conversion 'py2ri' not defined for objects of type '<class 'pandas.core.series.Series'>'\n",
      "  (name, str(e)))\n",
      "/Users/joshfeldman/Desktop/Projects/mice/venv/lib/python3.6/site-packages/rpy2/robjects/pandas2ri.py:67: UserWarning: Error while trying to convert the column \"velocity_OT_down_median_speed\". Fall back to string conversion. The error is: Conversion 'py2ri' not defined for objects of type '<class 'pandas.core.series.Series'>'\n",
      "  (name, str(e)))\n",
      "/Users/joshfeldman/Desktop/Projects/mice/venv/lib/python3.6/site-packages/rpy2/robjects/pandas2ri.py:67: UserWarning: Error while trying to convert the column \"velocity_OT_down_median_speed_active\". Fall back to string conversion. The error is: Conversion 'py2ri' not defined for objects of type '<class 'pandas.core.series.Series'>'\n",
      "  (name, str(e)))\n",
      "/Users/joshfeldman/Desktop/Projects/mice/venv/lib/python3.6/site-packages/rpy2/robjects/pandas2ri.py:67: UserWarning: Error while trying to convert the column \"velocity_OT_left_average_speed\". Fall back to string conversion. The error is: Conversion 'py2ri' not defined for objects of type '<class 'pandas.core.series.Series'>'\n",
      "  (name, str(e)))\n",
      "/Users/joshfeldman/Desktop/Projects/mice/venv/lib/python3.6/site-packages/rpy2/robjects/pandas2ri.py:67: UserWarning: Error while trying to convert the column \"velocity_OT_left_average_speed_active\". Fall back to string conversion. The error is: Conversion 'py2ri' not defined for objects of type '<class 'pandas.core.series.Series'>'\n",
      "  (name, str(e)))\n",
      "/Users/joshfeldman/Desktop/Projects/mice/venv/lib/python3.6/site-packages/rpy2/robjects/pandas2ri.py:67: UserWarning: Error while trying to convert the column \"velocity_OT_left_median_speed\". Fall back to string conversion. The error is: Conversion 'py2ri' not defined for objects of type '<class 'pandas.core.series.Series'>'\n",
      "  (name, str(e)))\n",
      "/Users/joshfeldman/Desktop/Projects/mice/venv/lib/python3.6/site-packages/rpy2/robjects/pandas2ri.py:67: UserWarning: Error while trying to convert the column \"velocity_OT_left_median_speed_active\". Fall back to string conversion. The error is: Conversion 'py2ri' not defined for objects of type '<class 'pandas.core.series.Series'>'\n",
      "  (name, str(e)))\n",
      "/Users/joshfeldman/Desktop/Projects/mice/venv/lib/python3.6/site-packages/rpy2/robjects/pandas2ri.py:67: UserWarning: Error while trying to convert the column \"velocity_OT_right_average_speed\". Fall back to string conversion. The error is: Conversion 'py2ri' not defined for objects of type '<class 'pandas.core.series.Series'>'\n",
      "  (name, str(e)))\n",
      "/Users/joshfeldman/Desktop/Projects/mice/venv/lib/python3.6/site-packages/rpy2/robjects/pandas2ri.py:67: UserWarning: Error while trying to convert the column \"velocity_OT_right_average_speed_active\". Fall back to string conversion. The error is: Conversion 'py2ri' not defined for objects of type '<class 'pandas.core.series.Series'>'\n",
      "  (name, str(e)))\n",
      "/Users/joshfeldman/Desktop/Projects/mice/venv/lib/python3.6/site-packages/rpy2/robjects/pandas2ri.py:67: UserWarning: Error while trying to convert the column \"velocity_OT_right_median_speed\". Fall back to string conversion. The error is: Conversion 'py2ri' not defined for objects of type '<class 'pandas.core.series.Series'>'\n",
      "  (name, str(e)))\n",
      "/Users/joshfeldman/Desktop/Projects/mice/venv/lib/python3.6/site-packages/rpy2/robjects/pandas2ri.py:67: UserWarning: Error while trying to convert the column \"velocity_OT_right_median_speed_active\". Fall back to string conversion. The error is: Conversion 'py2ri' not defined for objects of type '<class 'pandas.core.series.Series'>'\n",
      "  (name, str(e)))\n",
      "/Users/joshfeldman/Desktop/Projects/mice/venv/lib/python3.6/site-packages/rpy2/robjects/pandas2ri.py:67: UserWarning: Error while trying to convert the column \"velocity_OT_total_average_speed\". Fall back to string conversion. The error is: Conversion 'py2ri' not defined for objects of type '<class 'pandas.core.series.Series'>'\n",
      "  (name, str(e)))\n",
      "/Users/joshfeldman/Desktop/Projects/mice/venv/lib/python3.6/site-packages/rpy2/robjects/pandas2ri.py:67: UserWarning: Error while trying to convert the column \"velocity_OT_total_average_speed_active\". Fall back to string conversion. The error is: Conversion 'py2ri' not defined for objects of type '<class 'pandas.core.series.Series'>'\n",
      "  (name, str(e)))\n",
      "/Users/joshfeldman/Desktop/Projects/mice/venv/lib/python3.6/site-packages/rpy2/robjects/pandas2ri.py:67: UserWarning: Error while trying to convert the column \"velocity_OT_total_median_speed\". Fall back to string conversion. The error is: Conversion 'py2ri' not defined for objects of type '<class 'pandas.core.series.Series'>'\n",
      "  (name, str(e)))\n",
      "/Users/joshfeldman/Desktop/Projects/mice/venv/lib/python3.6/site-packages/rpy2/robjects/pandas2ri.py:67: UserWarning: Error while trying to convert the column \"velocity_OT_total_median_speed_active\". Fall back to string conversion. The error is: Conversion 'py2ri' not defined for objects of type '<class 'pandas.core.series.Series'>'\n",
      "  (name, str(e)))\n",
      "/Users/joshfeldman/Desktop/Projects/mice/venv/lib/python3.6/site-packages/rpy2/robjects/pandas2ri.py:67: UserWarning: Error while trying to convert the column \"velocity_OT_up_average_speed\". Fall back to string conversion. The error is: Conversion 'py2ri' not defined for objects of type '<class 'pandas.core.series.Series'>'\n",
      "  (name, str(e)))\n",
      "/Users/joshfeldman/Desktop/Projects/mice/venv/lib/python3.6/site-packages/rpy2/robjects/pandas2ri.py:67: UserWarning: Error while trying to convert the column \"velocity_OT_up_average_speed_active\". Fall back to string conversion. The error is: Conversion 'py2ri' not defined for objects of type '<class 'pandas.core.series.Series'>'\n",
      "  (name, str(e)))\n",
      "/Users/joshfeldman/Desktop/Projects/mice/venv/lib/python3.6/site-packages/rpy2/robjects/pandas2ri.py:67: UserWarning: Error while trying to convert the column \"velocity_OT_up_median_speed\". Fall back to string conversion. The error is: Conversion 'py2ri' not defined for objects of type '<class 'pandas.core.series.Series'>'\n",
      "  (name, str(e)))\n",
      "/Users/joshfeldman/Desktop/Projects/mice/venv/lib/python3.6/site-packages/rpy2/robjects/pandas2ri.py:67: UserWarning: Error while trying to convert the column \"velocity_OT_up_median_speed_active\". Fall back to string conversion. The error is: Conversion 'py2ri' not defined for objects of type '<class 'pandas.core.series.Series'>'\n",
      "  (name, str(e)))\n",
      "/Users/joshfeldman/Desktop/Projects/mice/venv/lib/python3.6/site-packages/rpy2/robjects/pandas2ri.py:67: UserWarning: Error while trying to convert the column \"velocity_closed_towards_middle_average_speed\". Fall back to string conversion. The error is: Conversion 'py2ri' not defined for objects of type '<class 'pandas.core.series.Series'>'\n",
      "  (name, str(e)))\n",
      "/Users/joshfeldman/Desktop/Projects/mice/venv/lib/python3.6/site-packages/rpy2/robjects/pandas2ri.py:67: UserWarning: Error while trying to convert the column \"velocity_closed_towards_middle_average_speed_active\". Fall back to string conversion. The error is: Conversion 'py2ri' not defined for objects of type '<class 'pandas.core.series.Series'>'\n",
      "  (name, str(e)))\n",
      "/Users/joshfeldman/Desktop/Projects/mice/venv/lib/python3.6/site-packages/rpy2/robjects/pandas2ri.py:67: UserWarning: Error while trying to convert the column \"velocity_closed_towards_middle_median_speed\". Fall back to string conversion. The error is: Conversion 'py2ri' not defined for objects of type '<class 'pandas.core.series.Series'>'\n",
      "  (name, str(e)))\n",
      "/Users/joshfeldman/Desktop/Projects/mice/venv/lib/python3.6/site-packages/rpy2/robjects/pandas2ri.py:67: UserWarning: Error while trying to convert the column \"velocity_closed_towards_middle_median_speed_active\". Fall back to string conversion. The error is: Conversion 'py2ri' not defined for objects of type '<class 'pandas.core.series.Series'>'\n",
      "  (name, str(e)))\n",
      "/Users/joshfeldman/Desktop/Projects/mice/venv/lib/python3.6/site-packages/rpy2/robjects/pandas2ri.py:67: UserWarning: Error while trying to convert the column \"velocity_closed_towards_outside_average_speed\". Fall back to string conversion. The error is: Conversion 'py2ri' not defined for objects of type '<class 'pandas.core.series.Series'>'\n",
      "  (name, str(e)))\n",
      "/Users/joshfeldman/Desktop/Projects/mice/venv/lib/python3.6/site-packages/rpy2/robjects/pandas2ri.py:67: UserWarning: Error while trying to convert the column \"velocity_closed_towards_outside_average_speed_active\". Fall back to string conversion. The error is: Conversion 'py2ri' not defined for objects of type '<class 'pandas.core.series.Series'>'\n",
      "  (name, str(e)))\n",
      "/Users/joshfeldman/Desktop/Projects/mice/venv/lib/python3.6/site-packages/rpy2/robjects/pandas2ri.py:67: UserWarning: Error while trying to convert the column \"velocity_closed_towards_outside_median_speed\". Fall back to string conversion. The error is: Conversion 'py2ri' not defined for objects of type '<class 'pandas.core.series.Series'>'\n",
      "  (name, str(e)))\n",
      "/Users/joshfeldman/Desktop/Projects/mice/venv/lib/python3.6/site-packages/rpy2/robjects/pandas2ri.py:67: UserWarning: Error while trying to convert the column \"velocity_closed_towards_outside_median_speed_active\". Fall back to string conversion. The error is: Conversion 'py2ri' not defined for objects of type '<class 'pandas.core.series.Series'>'\n",
      "  (name, str(e)))\n",
      "/Users/joshfeldman/Desktop/Projects/mice/venv/lib/python3.6/site-packages/rpy2/robjects/pandas2ri.py:67: UserWarning: Error while trying to convert the column \"velocity_open_towards_middle_average_speed\". Fall back to string conversion. The error is: Conversion 'py2ri' not defined for objects of type '<class 'pandas.core.series.Series'>'\n",
      "  (name, str(e)))\n",
      "/Users/joshfeldman/Desktop/Projects/mice/venv/lib/python3.6/site-packages/rpy2/robjects/pandas2ri.py:67: UserWarning: Error while trying to convert the column \"velocity_open_towards_middle_average_speed_active\". Fall back to string conversion. The error is: Conversion 'py2ri' not defined for objects of type '<class 'pandas.core.series.Series'>'\n",
      "  (name, str(e)))\n",
      "/Users/joshfeldman/Desktop/Projects/mice/venv/lib/python3.6/site-packages/rpy2/robjects/pandas2ri.py:67: UserWarning: Error while trying to convert the column \"velocity_open_towards_middle_median_speed\". Fall back to string conversion. The error is: Conversion 'py2ri' not defined for objects of type '<class 'pandas.core.series.Series'>'\n",
      "  (name, str(e)))\n",
      "/Users/joshfeldman/Desktop/Projects/mice/venv/lib/python3.6/site-packages/rpy2/robjects/pandas2ri.py:67: UserWarning: Error while trying to convert the column \"velocity_open_towards_middle_median_speed_active\". Fall back to string conversion. The error is: Conversion 'py2ri' not defined for objects of type '<class 'pandas.core.series.Series'>'\n",
      "  (name, str(e)))\n",
      "/Users/joshfeldman/Desktop/Projects/mice/venv/lib/python3.6/site-packages/rpy2/robjects/pandas2ri.py:67: UserWarning: Error while trying to convert the column \"velocity_open_towards_outside_average_speed\". Fall back to string conversion. The error is: Conversion 'py2ri' not defined for objects of type '<class 'pandas.core.series.Series'>'\n",
      "  (name, str(e)))\n",
      "/Users/joshfeldman/Desktop/Projects/mice/venv/lib/python3.6/site-packages/rpy2/robjects/pandas2ri.py:67: UserWarning: Error while trying to convert the column \"velocity_open_towards_outside_average_speed_active\". Fall back to string conversion. The error is: Conversion 'py2ri' not defined for objects of type '<class 'pandas.core.series.Series'>'\n",
      "  (name, str(e)))\n",
      "/Users/joshfeldman/Desktop/Projects/mice/venv/lib/python3.6/site-packages/rpy2/robjects/pandas2ri.py:67: UserWarning: Error while trying to convert the column \"velocity_open_towards_outside_median_speed\". Fall back to string conversion. The error is: Conversion 'py2ri' not defined for objects of type '<class 'pandas.core.series.Series'>'\n",
      "  (name, str(e)))\n",
      "/Users/joshfeldman/Desktop/Projects/mice/venv/lib/python3.6/site-packages/rpy2/robjects/pandas2ri.py:67: UserWarning: Error while trying to convert the column \"velocity_open_towards_outside_median_speed_active\". Fall back to string conversion. The error is: Conversion 'py2ri' not defined for objects of type '<class 'pandas.core.series.Series'>'\n",
      "  (name, str(e)))\n"
     ]
    }
   ],
   "source": [
    "miceDF = robjects.r('cross$pheno')\n",
    "miceDF = robjects.pandas2ri.ri2py_dataframe(miceDF)\n",
    "\n",
    "def extractNumber(mouseIDString):\n",
    "    indexStart = 5\n",
    "    indexEnd = mouseIDString.find('_')\n",
    "    return mouseIDString[indexStart:indexEnd]\n",
    "\n",
    "miceDF['mouseID'] = miceDF['id'].apply(lambda mouseIDString: extractNumber(mouseIDString))\n",
    "\n",
    "\n",
    "newFeaturesPath = 'all_the_data.csv'\n",
    "newFeaturesDF = pd.read_csv(newFeaturesPath, index_col=0)\n",
    "newFeaturesDF.set_index('mouse_details_mouseID', inplace=False)\n",
    "\n",
    "# Drop duplicate mouse IDs in new features\n",
    "newFeaturesDF = newFeaturesDF.drop_duplicates(subset='mouse_details_mouseID')\n",
    "\n",
    "mergedDF = pd.merge(\n",
    "    miceDF, \n",
    "    newFeaturesDF, \n",
    "    left_on='mouseID', \n",
    "    right_on='mouse_details_mouseID',\n",
    "    how='left'\n",
    ")\n",
    "\n",
    "cross_R_DF = robjects.pandas2ri.py2ri(mergedDF)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 22,
   "metadata": {},
   "outputs": [],
   "source": [
    "goodFeatures = [\n",
    "    'fraction_in_arms_closed',\n",
    "    'fraction_in_arms_middle',\n",
    "    'mouse_length',\n",
    "    'peeking_average_length_total',\n",
    "    'rest_fraction_all_arms',\n",
    "    'rest_fraction_closed_arms',\n",
    "    'rest_fraction_open_arms',\n",
    "    'turning_preferences_fraction_back',\n",
    "    'turning_preferences_fraction_left',\n",
    "    'turning_preferences_fraction_right',\n",
    "    'turning_preferences_fraction_straight',\n",
    "    'velocity_closed_towards_outside_average_speed_active',\n",
    "    'velocity_open_towards_middle_average_speed_active',\n",
    "    'velocity_open_towards_outside_average_speed_active'\n",
    "]"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 23,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/Users/joshfeldman/Desktop/Projects/mice/venv/lib/python3.6/site-packages/rpy2/robjects/pandas2ri.py:191: FutureWarning: from_items is deprecated. Please use DataFrame.from_dict(dict(items), ...) instead. DataFrame.from_dict(OrderedDict(items)) may be used to preserve the key order.\n",
      "  res = PandasDataFrame.from_items(items)\n"
     ]
    }
   ],
   "source": [
    "%%R -i goodFeatures,cross_R_DF\n",
    "goodFeatures <- goodFeatures\n",
    "for (feature in goodFeatures){\n",
    "    cross$pheno[,feature] <- as.numeric(cross_R_DF[,feature])\n",
    "}"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 24,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "    F2 intercross\n",
       "\n",
       "    No. individuals:    1571 \n",
       "\n",
       "    No. phenotypes:     35 \n",
       "    Percent phenotyped: 81.6 \n",
       "\n",
       "    No. chromosomes:    24 \n",
       "        Autosomes:      1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 \n",
       "                        23 \n",
       "        X chr:          X \n",
       "\n",
       "    Total markers:      51739 \n",
       "    No. markers:        3680 2706 3346 3181 3273 2538 2402 2543 2012 1806 2183 \n",
       "                        1950 1134 1704 1529 1786 938 1543 1309 1853 2228 1588 \n",
       "                        1647 2860 \n",
       "    Percent genotyped:  99.1 \n",
       "    Genotypes (%):    \n",
       "          Autosomes:        AA:23.6      AB:51.6      BB:24.8  not BB:0.0  \n",
       "                        not AA:0.0  \n",
       "       X chromosome:        AA:21.3     ABf:19.7     ABr:6.2       BB:0.4  \n",
       "                            AY:24.1      BY:28.3 \n"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    }
   ],
   "source": [
    "%%R \n",
    "print(summary(cross))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.6.6"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
